### ISSUE TITLE
Ar Check Internal Error

### ISSUE THREAD

**Issue by airmyles** [Armarr/Autorank-2#11]
I'm running stats hooked up with AutoRank. When players use ar check command it says an internal error has occurred. Auto Ranking of players does not work. I only base it off of time played, blocks broken, and blocks changed. I am using the most recent version of Stats and AutoRank. This is what is on console

http://pastebin.com/kgfDSKPh

**Comment by JINXADORE** [comment]
Hey ,

we have a Server and we are Trying to do a Advanced config edit but we fail every time.

We ask around and noone could help us so the Author is the last posibility.

Could you please help and tell us the reason why the config is still Invaild and Groups are not defined ?

 

This is a debug file of Autorank. You should give this to an author or ticket manager of Autorank.
You can go to http://pastebin.com/ and paste this file. Then, give the link and state the problems you're having in a ticket on the Autorank page.

Date created: 2019-07-07 16:33:54

Autorank version: 3.7.2

Server implementation: git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)

Server version: 1.7.10-R0.1-SNAPSHOT

Server warning state: DEFAULT

Ranks defined:

------------------- ChangeGroup debug info ------------------- 
Group: Nomad
- Nomad
- 1 requirements
- 3 results
----------------------------
Group: Vagabond
- Vagabond
- 1 requirements
- 3 results
----------------------------
Group: Drifter
- Drifter
- 1 requirements
- 3 results
----------------------------
Group: Scarab
- Scarab
- 1 requirements
- 3 results
----------------------------
Group: Seeker
- Seeker
- 1 requirements
- 3 results
----------------------------
Group: Dunewalker
- Dunewalker
- 1 requirements
- 3 results
----------------------------
Group: Sandstalker
- Sandstalker
- 1 requirements
- 3 results
----------------------------
Group: Pharaoh
- Pharaoh
- 1 requirements
- 3 results
----------------------------
Group: Inquisitor
- Inquisitor
- 1 requirements
- 3 results
----------------------------

Config used: AdvancedConfig.yml

Using MySQL: false

Java version: 10.0.2

Operating system: Windows 10

OS version: 10.0

OS architecture: amd64

Loaded addons: []

 

 

Thank you !
