### ISSUE TITLE
Invalid groups

### ISSUE THREAD

**Issue by Spence09** [Armarr/Autorank-2#111]
Hello, Autorank is starting correctly but gives a sever error.
[SEVERE] [Autorank] There are invalid groups defined in the config!
[SEVERE] [Autorank] Check your config!

Iv checked the config and from what i can tell everything is correct.

I also get this message in game when the auto-rank is supposed to occur

"Permissions group is not defined in permissions file: Stranger

Iv done a ton of searching on this and i cant seem to figure it out. seems like a simple fix. but im overlooking something. any assistance would be appreciated. also im rather new to minecraft servers.

EDIT: ok, so after making a few adjustments im at a point where in game it says:
    "Rank change of rank 'stranger' is invalid.
    "The rank to promote to doesn't exist in the perm file"

I also used a YAML parser and found no issues.

again any assistance would be appreciated.

**Comment by visionfear** [comment]
got the same problem

**Comment by visionfear** [comment]
fixed the problem. remember to not have any space in the config ;)
