### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mats165** [Armarr/Autorank-2#136]
Hello, 

I think i configured every aspect of the plugin right, but whenever i try to test it, it says:

"{player} has player for {amount} and is in {rank}, requirements to be ranked up: none"

So apparently it notices what rank I am in, that i played a certain amount of time, but not that I match the requirements to rank up! What did i do wrong? Thanks in advance!

Configs:
http://pastebin.com/wvPpesiV
http://pastebin.com/aw0QAaN6

**Comment by Staartvin** [comment]
Closed due to inactivity and inrelevance.
