### ISSUE TITLE
Issue Resolved

### ISSUE THREAD

**Issue by Rage170668** [Armarr/Autorank-2#140]
I am currently trying to get Autorank working i have these errors in the console.
31.10 06:29:01 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:73)
31.10 06:29:01 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:46)
 
Heres a Debug report:
This is a debug file of Autorank. You should give this to an author or ticket manager of Autorank.
You can go to http://pastebin.com/ and paste this file. Then, give the link and state the problems you're having in a ticket on the Autorank page.

Date created: 2014-10-31 06:49:46

Autorank version: 3.3

Server implementation: git-MCPC-Plus-575dff4 (MC: 1.4.7)

Server version: 1.4.7-R1.1-SNAPSHOT

Server warning state: DEFAULT

Ranks defined: 

- Emerald: TimeRequirement -> RankChangeResult, MessageResult
- Sapphire: TimeRequirement -> RankChangeResult, MessageResult
- Member: TimeRequirement -> RankChangeResult, MessageResult
- Quartz: TimeRequirement -> RankChangeResult, MessageResult
- Ruby: TimeRequirement -> RankChangeResult, MessageResult
- Gold: TimeRequirement -> RankChangeResult, MessageResult
- Coal: TimeRequirement -> RankChangeResult, MessageResult
- Iron: TimeRequirement -> RankChangeResult, MessageResult

Config used: SimpleConfig.yml

Using MySQL: false

Java version: 1.7.0_67

Operating system: Linux

OS version: 3.10.23-xxxx-std-ipv6-64

OS architecture: amd64

Loaded addons: []

Thanks For the Help,
Rage

**Comment by Staartvin** [comment]
Closed due to resolution found.
