### ISSUE TITLE
Autorank not counting

### ISSUE THREAD

**Issue by Beerolopis** [Armarr/Autorank-2#148]
I have an issue with autorank not counting. For example, when somebody has to kill 5 pigs to rank up, even if they kill 99999 pigs they wont be able to rank up. Can anyone help?
Yes, I have both vault and stats installed.

Advanced config:
http://pastebin.com/CLwWewwV

Settings.yml:
http://pastebin.com/B5i0VXcr

Stats:
config.yml: (I took out the MySQL data in the paste, however it is included in the actual config)
http://pastebin.com/7jdtQKUk

**Comment by Staartvin** [comment]
Closed due to inactivity.
