### ISSUE TITLE
UnhandledException

### ISSUE THREAD

**Issue by TheChampTF** [Armarr/Autorank-2#155]
Running on CraftBukkit version git-Bukkit-b389396 (MC: 1.8)
Issue seams to be connected to PermissionsEx, EssentialsSpawn and Autorank
Plugins: Autorank v3.4 , PermissionsEx v1.23 and EssentialsSpawn vTeamCity(By the Spigot team)

Errors:

26.12 21:03:24 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_03]
26.12 21:03:24 [Server] INFO at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0_03]
26.12 21:03:24 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_03]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInClientCommand.a(SourceFile:8) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInClientCommand.a(SourceFile:31) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1283) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:448) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:508) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at com.earth2me.essentials.spawn.EssentialsSpawn$1.execute(EssentialsSpawn.java:51) ~[?:?]
26.12 21:03:24 [Server] INFO at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.onPlayerRespawn(EssentialsSpawnPlayerListener.java:65) ~[?:?]
26.12 21:03:24 [Server] INFO at com.earth2me.essentials.User.getGroup(User.java:670) ~[?:?]
26.12 21:03:24 [Server] INFO at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:42) ~[?:?]
26.12 21:03:24 [Server] INFO at com.earth2me.essentials.perm.PermissionsExHandler.getGroup(PermissionsExHandler.java:23) ~[?:?]
26.12 21:03:24 [Server] INFO at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:171) ~[?:?]
26.12 21:03:24 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.nameToUUID(PermissionsEx.java:356) ~[?:?]
26.12 21:03:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.getOfflinePlayer(CraftServer.java:1242) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.UserCache.getProfile(SourceFile:118) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.UserCache.c(SourceFile:170) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at net.minecraft.server.v1_8_R1.UserCache.a(SourceFile:186) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at com.google.common.collect.Lists.newArrayList(Lists.java:147) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at com.google.common.collect.Iterators.addAll(Iterators.java:357) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at com.google.common.collect.Iterators$9.next(Iterators.java:939) ~[custom.jar:git-Bukkit-b389396]
26.12 21:03:24 [Server] INFO at java.util.LinkedList$ListItr.next(Unknown Source) ~[?:1.7.0_03]
26.12 21:03:24 [Server] INFO at java.util.LinkedList$ListItr.checkForComodification(Unknown Source) ~[?:1.7.0_03]
26.12 21:03:24 [Server] INFO java.util.ConcurrentModificationException
26.12 21:03:24 [Server] ERROR Could not pass event PlayerRespawnEvent to EssentialsSpawn vTeamCity

26.12 21:05:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
26.12 21:05:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
26.12 21:05:34 [Server] INFO at me.armar.plugins.autorank.leaderboard.Leaderboard$2.run(Leaderboard.java:84)
26.12 21:05:34 [Server] INFO at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:185)
26.12 21:05:34 [Server] INFO at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(Leaderboard.java:106)
26.12 21:05:34 [Server] INFO at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:113)
26.12 21:05:34 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.playerHas(Permission_PermissionsEx.java:298)
26.12 21:05:34 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:247)
26.12 21:05:34 [Server] INFO at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:171)
26.12 21:05:34 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.nameToUUID(PermissionsEx.java:356)
26.12 21:05:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.getOfflinePlayer(CraftServer.java:1242)
26.12 21:05:34 [Server] INFO at net.minecraft.server.v1_8_R1.UserCache.getProfile(SourceFile:118)
26.12 21:05:34 [Server] INFO at net.minecraft.server.v1_8_R1.UserCache.c(SourceFile:170)
26.12 21:05:34 [Server] INFO at net.minecraft.server.v1_8_R1.UserCache.a(SourceFile:186)
26.12 21:05:34 [Server] INFO at com.google.common.collect.Lists.newArrayList(Lists.java:147)
26.12 21:05:34 [Server] INFO at com.google.common.collect.Iterators.addAll(Iterators.java:357)
26.12 21:05:34 [Server] INFO at com.google.common.collect.Iterators$9.next(Iterators.java:939)
26.12 21:05:34 [Server] INFO at java.util.LinkedList$ListItr.next(Unknown Source)
26.12 21:05:34 [Server] INFO at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
26.12 21:05:34 [Server] INFO Caused by: java.util.ConcurrentModificationException
26.12 21:05:34 [Server] INFO at java.lang.Thread.run(Unknown Source)
26.12 21:05:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
26.12 21:05:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
26.12 21:05:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
26.12 21:05:34 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4 generated an exception while executing task 81
26.12 21:05:34 [Server] WARN Exception in thread "pool-3-thread-8"

**Comment by TheChampTF** [comment]
I might found the cause:

02.01 02:32:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
02.01 02:32:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
02.01 02:32:38 [Server] INFO at me.armar.plugins.autorank.leaderboard.Leaderboard$3.run(Leaderboard.java:129)
02.01 02:32:38 [Server] INFO at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:185)
02.01 02:32:38 [Server] INFO at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(Leaderboard.java:106)
02.01 02:32:38 [Server] INFO at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:113)
02.01 02:32:38 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.playerHas(Permission_PermissionsEx.java:298)
02.01 02:32:38 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:247)
02.01 02:32:38 [Server] INFO at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:174)
02.01 02:32:38 [Server] INFO Caused by: java.lang.NullPointerException
02.01 02:32:38 [Server] INFO at java.lang.Thread.run(Unknown Source)
02.01 02:32:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
02.01 02:32:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
02.01 02:32:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
02.01 02:32:38 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4 generated an exception while executing task 37785
02.01 02:32:38 [Server] WARN Exception in thread "pool-3-thread-7"

Happened when closing the server down.

**Comment by Staartvin** [comment]
It seems that Pex is having some problems getting the player, are you running the latest version?

**Comment by TheChampTF** [comment]
Yes

**Comment by Staartvin** [comment]
Can you update to dev build 313? I changed code around for the leaderboard.

**Comment by TheChampTF** [comment]
Would love to, but dev. server seams down

**Comment by TheChampTF** [comment]
[18:47:28 ERROR]: Error occurred while enabling Autorank v3.4-Dev-317 (Is it up to date?)
java.lang.NullPointerException
	at me.armar.plugins.autorank.config.ConfigHandler.getRequirements(ConfigHandler.java:128) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.builders.RankChangeBuilder.createFromAdvancedConfig(RankChangeBuilder.java:42) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.PlayerChecker.initialiseFromConfigs(PlayerChecker.java:179) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:392) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Bukkit-5e6c347]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit.jar:git-Bukkit-5e6c347]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-5e6c347]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:340) [craftbukkit.jar:git-Bukkit-5e6c347]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:312) [craftbukkit.jar:git-Bukkit-5e6c347]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit.jar:git-Bukkit-5e6c347]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit.jar:git-Bukkit-5e6c347]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit.jar:git-Bukkit-5e6c347]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit.jar:git-Bukkit-5e6c347]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:473) [craftbukkit.jar:git-Bukkit-5e6c347]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by Staartvin** [comment]
Can you show me your advancedconfig?

**Comment by TheChampTF** [comment]
Used the new build you released and found the lines with the wrong code in. Thanks a lot!

**Comment by Staartvin** [comment]
Great!
