### ISSUE TITLE
Autorank whois integration

### ISSUE THREAD

**Issue by Apakura** [Armarr/Autorank-2#160]
Hiyas!

Was curious to know if someone would be able to add the option for Autorank to look at the whois location GeoIP of a player to allow it to be a requirement for a rank change.

We are wanting to add a rank up based on the GeoIP of a player, EssentialsGeoIP provides the means to get the location, just unsure how to make AutoRank co-operate.

Any help would be wonderfully appreciated.

**Comment by Staartvin** [comment]
At the moment, this is not possible. I can however look into the possibilty of adding this as a feature to Autorank ;)

**Comment by Apakura** [comment]
That would be auesome!

**Comment by Staartvin** [comment]
The new dev build has support for GeoIp built in, but it has not been tested yet.

**Comment by Apakura** [comment]
Awesome! Thanks so much!

**Comment by opze** [comment]
Hey, I'm the owner/operator of the server Apakura has requested this feature for.

I've given the latest dev build a test and I've encountered some issues.

After adding the Location requirement for one rank, when doing /ar check I'm greeted by "An internal error occurred while attempting to perform this command" in game, whilst this error is displayed to the console: http://pastebin.com/pmLzSiNu

After removing the requirement, thus turning my advanced config into it's previously functional state, I'm seeing this error when doing /ar check http://pastebin.com/WtgYr9VL

Regards.

**Comment by Staartvin** [comment]
You are getting this error because you are using the wrong location requirement. You are using 'location' instead of 'essentials geoip location'. The normal location one is used to define a location inside the minecraft world. See https://github.com/Armarr/Autorank-2/blob/master/AdvancedConfig.yml#L71 for more information. I'm not sure if the requirement is working yet, as I couldn't test it. My Essentials plugin keeps crashing on 1.8. Which version of Essentials are you using?

**Comment by opze** [comment]
Hey, I was using 'essentials geoip location' as per that file originally. It's what produced the aforementioned error.

As for essentials, I'm using 2.13.1 and I'm still on 1.7.10 (Cauldron) not 1.8.

**Comment by Staartvin** [comment]
Hmm, then it's something I did wrong with the code.

**Comment by Staartvin** [comment]
Try dev build 316 and let me know if you have any problems.

**Comment by opze** [comment]
Hey, Thanks a lot for that it appears to be working.

One additional request I have that I thought I was able to do from the beginning is to have multiple requirements for one requirement if that makes sense.

I only need it for this location of that makes it easier. 

Essentially, I'd like to use this as somewhat of a grey list making players from x, x, x country promoted to a rank with build rights etc on join.

So in requirements, I'd like to be able to do something like this, and it will complete the requirement if they meet any of one them.

Example of what I'd like to do:
    Guest:
        requirements:
            essentials geoip location:
                value: Australia, New Zealand

So the requirement would be from Australia or New Zeland, not just one and not the other.

Regards.

**Comment by Staartvin** [comment]
I can work on a system that allows you to implement 'OR' statements. You'll have to give me some time though, it could take a while.

**Comment by Staartvin** [comment]
I implemented this in dev build 352.
