### ISSUE TITLE
AutoRank not displaying names on leaderboard

### ISSUE THREAD

**Issue by xBL0X** [Armarr/Autorank-2#161]
When I use my /ar check command on my server it says I have 8h 39m played and that is equal to what it says in the Data.yml file. The only problem is when I type /ar leaderboard, My name is nowhere to be found on it. I am using latest (v3.4) and have MySQL turned on and synced. I can provied any additional data you need.

xBL0X

Debug: http://pastebin.com/VDMQ4KdU

**Comment by Staartvin** [comment]
Try '/ar leaderboard force'. If thats not doing anything, turn on debug in the settings config and check if there are update message in the console.

**Comment by xBL0X** [comment]
It worked until I did the command /ar reload then my name disappeared from the leaderboard again. Debug doe not seem to show anything important relating to leaderboards, but here is my console after a multitude of AR commands.

Console with debug on: http://pastebin.com/LE3Kr6iQ
Appreciate the replies, gotta love a dev who actually helps.

**Comment by Staartvin** [comment]
Hmm, is it right that you disable Autorank manually? Autorank keeps getting disabled. There should be nothing wrong with the leaderboard. It's updating correctly and show correct debug information.

**Comment by xBL0X** [comment]
No, I have not yet disabled AutoRank on my own, i didn't even know there was that option... I am in a lot of confusion as I could do /ar reload 10 times and it still shows properly then maybe I'd do it an 11th time (just an example number) and I would then be off the leaderboard.

**Comment by xBL0X** [comment]
Okay I can\t duplicate the image as of 2015/1/14 so don't bother putting any time into the error, I'll update you if it reoccurs.
Thanks Staartvin!

**Comment by Staartvin** [comment]
Hmm, I have fixed feelings. It should always work!  Why are you reloading exactly?

**Comment by xBL0X** [comment]
Okay I regret to inform you the error occurred again, and it turns out this time that maybe it was from a server reload (???) I'm not quite sure to be honest it seems to be at almost random. I have one more trick up my sleeve that I will try.

**Comment by xBL0X** [comment]
I greatly apologize if this is causing you any type of spam but I am excited that I may have found it... it seems either when I am opped on my server or am in the Owner rank, it excludes me from the leaderboard. Maybe that will help you?

**Comment by Staartvin** [comment]
Hmm, could it be that your '*' permission is causing you to be excluded from the leader board?

**Comment by xBL0X** [comment]
It may be because it is definitely when I am Owner rank then do /ar leaderboard or /ar leaderboard force I am no longer there D: What would you suggest me changing? To keep me from being exempt from the leaderboard...

**Comment by Staartvin** [comment]
Hmm, what permission plugin are you using?

**Comment by xBL0X** [comment]
GroupManager, I am fairly familiar with it. If needed I have full plugins list...

**Comment by Staartvin** [comment]
Can you show me your permissions file?

**Comment by xBL0X** [comment]
Sure thing: http://pastebin.com/iSfCNVp3

**Comment by Staartvin** [comment]
Could you add a negation permission for the leader board? autorank.leaderboard.exempt?

**Comment by xBL0X** [comment]
Done, seems to be all fixed. Thanks kindly my friend.

**Comment by Staartvin** [comment]
Great to hear, thanks for using Autorank!
