### ISSUE TITLE
“Autorank is disabled. Check your server.log!”

### ISSUE THREAD

**Issue by Ser3196** [Armarr/Autorank-2#163]
http://pastebin.com/fvieKnXa here is the server.log
and the advanced config is here
Ranks:
    MiniJugador:
        requirements:
            time:
                value: 10h
        results:
            rank change: MiniJugador;Jugador
            command: 'say &p ha tenido una promocion; broadcast &p ahora es Jugador!'
            message: 'Enhorabuena, ahora eres un Jugador.'
    Jugador:
        requirements:
            time:
                value: 10d
            exp:
                value: 20
            mobs killed:
                value: 10;chicken
        results:
            rank change: Jugador;GranJugador
            command: 'say &p ha tenido una promocion; bc &p ahora es un Gran Jugador!'
            message: 'Enhorabuena, ahora eres un Gran Jugador. De los grandes.'
    GranJugador:
        requirements:
            time:
                value: 24h
            exp:
                value: 60
            mobs killed:
                value: 30;chicken
            players killed:
                value: 20
        results:
            rank change: GranJugador;Campeon
            commnad: 'say &p ha tenido una promocion; bc &p ahora es un Campeon!'
            message: 'Enhorabuena, ahora eres un CampeÃ³n'
    Campeon:
        requirements:
            time:
                value: 3d
            exp:
                value: 140
            mobs killed:
                value: 300;chicken
            mobs killed2:
                value: 50;cow
            players killed:
                value: 100
        results:
            rank change: Campeon;GranCampeon
            command: 'say &p ha tenido una promocion; bc &p ahora es un Gran Campeon!'
            message: 'Enhorabuena, ahora eres un Gran Campeon. El mas grande de los campeones.'
    GranCampeon:
        requirements:
            time: 
                value: 5d
            exp:
                value: 180
            mobs killed:
                value: 540;chicken
            mobs killed2:
                value: 100;cow
            mobs killed3:
                value: 400;zombie   
            mobs killed4:
                value: 350;skeleton
            has item:
                value: 265;64
            players killed:
                value: 200
        results:
            rank change: GranCampeon;Leyenda
            command: 'say &p ha tenido una promocion; bc &p ahora es una Leyenda!; eco give &p 1000'
            message: 'Enhorabuena, ahora eres una Leyenda. Aunque no lo creas, es verdad. Eres una leyenda!'
    Leyenda:
        requirements:
            time:
                value: 8d
            exp:
                value: 290
            mobs killed:
                value: 1000;chicken
            mobs killed2:
                value: 500;cow
            mobs killed3:
                value: 800;zombie
            mobs killed4:
                value: 794;skeleton
            mobs killed5:
                value: 600;mushroomcow
            has item:
                value: 265;256
            has item2:
                value: 266;300
            players killed:
                value: 1000
        results:
            rank change: Leyenda;Elite
            command: 'say &p ha tenido una promocion; bc &p ahora es un Elite!; csgive 272#2 1 &p'
            message: 'Enhorabuena, eres el mejor. El mejor de lo mejor, el mejor de todos los rangos, un verdadero Elite.'
#################
I tried to update the plugin, but goes bug alike.
I have Vault, stats, essentials and chestshop.
Can help me?

**Comment by Staartvin** [comment]
Is Stats enabled properly? This is probably the case.

**Comment by Ser3196** [comment]
Yes, I found the bug and solved. Thanks for the help

The bug was Stats plugin, in the end I removed it because I did not know how
to configure it with that of SQL

2015-01-13 18:13 GMT-03:00 Staartvin <notifications@github.com>:

**Comment by Staartvin** [comment]
Good to hear you fixed it.
