### ISSUE TITLE
Region Detection Bug

### ISSUE THREAD

**Issue by tincopper2** [Armarr/Autorank-2#165]
Hello, I cannot have it where the users have to have all of the requirements before they rankup, and have it show which ones they have and not? EG: they get to level 10, but then die and reset, but in autorank it counts as completing. Is there anyway to fix this? If stats change? I primarily need this because I want them to only rankup if they meet all requirements AND walk through a portal, it works somewhat, but they can walk in the portal first then meet all requirements after, which they get teleported wherever they meet up the rest of the requirements, I want it to only allow them to be ranked up while they are standing in a certain region.

**Comment by Staartvin** [comment]
If you want players to have all the requirements meet at the same time, you'll need to set 'use partial completion' to false.

**Comment by tincopper2** [comment]
Then it doesn't say which ones they have completed at that moment.

**Comment by Staartvin** [comment]
Ah, okay. I'll have to change that. So it doesn't show the 'done' part if partial completion is off?

**Comment by tincopper2** [comment]
Yes it just lists all requirements.

**Comment by tincopper2** [comment]
Is this fixed, if so, what version/build number?

**Comment by Staartvin** [comment]
I will not be able to add this feature, as it is impossible to add at this moment.
