### ISSUE TITLE
AutoRank Leaderboard (3.1 for MC 1.7.10)

### ISSUE THREAD

**Issue by Lydyn** [Armarr/Autorank-2#167]
AutoRank Version: 3.1

What storage option are you using?  YML for AutoRank, since I'm not sure what our current, ongoing MySQL would do. Maybe that's the issue?

What steps will reproduce the problem?
1. Simple, dropped the jar into the server.
2. /ar leaderboard
3. Every single rank in this board is incorrect, time-wise. We have members saying they've played for 24 hours when they've only player 18 hours (according to /ar check, which is far more accurate).

What is the expected output? What do you see instead?
Expected output is that the leader board will show accurate times according who's played the most. I see a jumbled mess of random times for random players.

Do you have an console log of what happened?
Log doesn't show anything special.

Please provide any additional information below.
None to report.

**Comment by Staartvin** [comment]
Could you do '/ar leaderboard force' and see if this updates the leaderboard?

**Comment by Lydyn** [comment]
I can and while it does switch the players around, all the play times are wrong still.  Strangely enough, the times are very similar from before, making it seem like AutoRank isn't fetching the correct player names.

/AR LEADERBOARD
-------- Autorank Leaderboard --------
1 | xanthos1 - 1 day(s), 1 hour(s) and 0 minute(s).
2 | Pornopack - 0 day(s), 23 hour(s) and 20 minute(s).
3 | REEAADDYY - 0 day(s), 22 hour(s) and 20 minute(s).
4 | LILPRO911 - 0 day(s), 20 hour(s) and 55 minute(s).
5 | Sir_Ald - 0 day(s), 18 hour(s) and 45 minute(s).

/AR LEADERBOARD FORCE
-------- Autorank Leaderboard --------
1 | Wholockgal - 1 day(s), 1 hour(s) and 0 minute(s).
2 | Sir_Ald - 0 day(s), 23 hour(s) and 20 minute(s).
3 | REEAADDYY - 0 day(s), 22 hour(s) and 20 minute(s).
4 | PIE7171 - 0 day(s), 22 hour(s) and 0 minute(s).
5 | LILPRO911 - 0 day(s), 20 hour(s) and 55 minute(s).

**Comment by Staartvin** [comment]
What did plugin did you set to fetch the times for Autorank? E.g. what is the option 'use time of' set  to?

**Comment by Lydyn** [comment]
AutoRank, as by default. I /had/ OnTime, but that plugin was having a lot of issues and I've since disabled it.

**Comment by Staartvin** [comment]
When you use a different timing plugin, the leader board will still use the local Autorank files, so that's why the leaderboard is off. However, if you've switched to Autorank as default it should display the same playtime as /ar check does.

**Comment by Lydyn** [comment]
Well, I meant to say, I was using OnTime before AutoRank even being installed, disabled it, and installed AutoRank and left the "use time of" as default (AutoRank).

**Comment by Staartvin** [comment]
Ah, well then there should be no problem. Hmm, could you turn on debug and let it run for a while. Could you also try to update to Dev build 317? This might the leaderboard thing

**Comment by Lydyn** [comment]
Well, I run a 1.7.10 modded server... so unless I understand plugins wrong, I can't use anything that wants a higher game version. I'll try looking into how to turn debug on. ^.^

**Comment by Staartvin** [comment]
You should be able to run that version of Autorank on 1.7.10

**Comment by Lydyn** [comment]
Sorry for leaving this open. Busy life and we're trying to see if we can handle switching to a lower key server right now since there's only a few of us. I plan on trying this when I can.

**Comment by Staartvin** [comment]
Closed due to inactivity.
