### ISSUE TITLE
No blockcount in ranking

### ISSUE THREAD

**Issue by Titanzi** [Armarr/Autorank-2#168]
I have a strange problem.
When I'm testing the plugin for rankup from rank "Stranger" to rank "Peasant" it do count the time I have set, 1 minutes. But I have also set 10;90 as an mob-kill requirement. (kill 10 pigs)
The plugin does say that the time limit has been met but even after killing 10 pigs and waiting for the plugin to re-poll, it still ain't  updating the mobs-killed requirement.

My config file atm.
http://i.imgur.com/3D91efa.png?1

**Comment by Staartvin** [comment]
Do you have Stats installed?

**Comment by Titanzi** [comment]
Hello.
No I do not. thanks for the info :)

2015-01-29 15:15 GMT+01:00 Staartvin <notifications@github.com>:

> Do you have Stats installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Armarr/Autorank-2/issues/168#issuecomment-72030960>.
>



-- 
Please think about the environment before printing this e-mail
More information at: www.thinkbeforeprinting.org

**Comment by Staartvin** [comment]
Fixed issue.
