### ISSUE TITLE
Autorank is disabled. Check your server.log!

### ISSUE THREAD

**Issue by fenman10** [Armarr/Autorank-2#169]
Whenever I change the name of the groups in my Autorank advancedconfig.yml and do /ar reload on the server it works fine. As soon as I restart the server and I then try a /ar command of any sort it comes up with this error "Autorank is disabled. Check your server.log!"

I removed Stats as an act of troublshooting so I'm aware there are some errors saying stats isn't enabled. Here is a pastebin of the server log. http://pastebin.com/mxq7GacQ

**Comment by fenman10** [comment]
Bump

**Comment by fenman10** [comment]
http://pastebin.com/zpYLcNkZ

**Comment by Staartvin** [comment]
Your rank changes are invalid, check the wiki for more information on that.

**Comment by fenman10** [comment]
Could you please be more specific? I've been looking at the wikipedia for days haha :)

**Comment by Staartvin** [comment]
Well the rank changes of the groups are not valid. They should be 'rankfrom;rankto', but you only have rankto

**Comment by fenman10** [comment]
I tried doing "rankfrom;rankto", "rankfrom;rankto;world" and I also tried "rankto" on it's own. None of the three seem to work for me. I started with "rankfrom;rankto" and so I started troubleshooting and trial and improving.

I tried removing the stats plugin and doing it and still nothing wants to work

**Comment by Staartvin** [comment]
Can I see your config with the 'rankfrom;rankto' ones?

**Comment by fenman10** [comment]
Sure. Here it is http://pastebin.com/kHx5bYCa

**Comment by Staartvin** [comment]
Your results are in a requirement. Thus they will oly be performed if that one requirement is completed. You should put the results outside the requirement, take a look at the advancedconfig on the wiki.

**Comment by fenman10** [comment]
Alright I've tried that and it still doesn't work. http://pastebin.com/zL33B8a0

**Comment by Staartvin** [comment]
Does it give any errors?

**Comment by fenman10** [comment]
In the console? I'll check again

**Comment by fenman10** [comment]
This is everything about Autorank in the console while the server was turning on that I was aware of. http://pastebin.com/EHrsPdRS

This is the whole log from when I turned it on. http://pastebin.com/giiA22ri

**Comment by Staartvin** [comment]
Autorank doesn't recognise the sheep sheared requirement as it is not a valid one ;)
It's 'times sheared'

**Comment by fenman10** [comment]
Yes it worked! I also just realised I did "Sheeps" as opposed to "Sheep" but that wouldn't have worked anyway! Thank you so much! :)

**Comment by Staartvin** [comment]
Great, that's good to hear.
