### ISSUE TITLE
mcmmo power level

### ISSUE THREAD

**Issue by Ironic8b498** [Armarr/Autorank-2#176]
OK tried the 3.4 stable version and it gave error in logs at boot up.  I am running Spigot 1.8. So I am attempting to use Autorank-3.4-Dev-353, no error at boot up but I have 3  mcmmo skill level requirements for first rank up and the only one seen is last one in config for that rank. 

I also get an error in logs also this is for second rank-up. and when at the second rank and I use the /ar check command I get internal error in chat which I believe is caused by the following error.
[20:34:39] [Server thread/ERROR]: [Autorank] Could not setup requirement 'mcmmo power level'! It's invalid: check the wiki for documentation.

My third rank up uses 13 different mcmmo skill levels and only one is seen, the last one in the list again. 

is it possible to use more then one mcmmo skill level?

**Comment by Staartvin** [comment]
Can you show me your config?

**Comment by Ironic8b498** [comment]
here my autorank config http://pastebin.com/EaCHGSus

**Comment by Staartvin** [comment]
If you have more than one of any kind of requirement or result, you will need to add a number. So mcmmo skill level1, mcmmo skill level2, etc.

**Comment by Ironic8b498** [comment]
Ok that fixes one of my two problems still not sure why I get a error when I want to use mcmmo power level

**Comment by Ironic8b498** [comment]
Thanks, must of been the reason why I couldn't use mcmmo power level it now works also

**Comment by Staartvin** [comment]
You'll have to find the uuid of the player and look in the playerdata.yml. You can delete the complete progress list of that player.

**Comment by Ironic8b498** [comment]
Thanks

**Comment by Staartvin** [comment]
If you get the 'already completed rank' message, you'll have to enable 'infinite ranking'.

**Comment by Ironic8b498** [comment]
thanks I was able to find setting that will allow me to run my server the way I had been before your plugin, just less work on my part

**Comment by Staartvin** [comment]
Good to hear, thanks for using Autorank! :)
