### ISSUE TITLE
Mysql question

### ISSUE THREAD

**Issue by devryb** [Armarr/Autorank-2#177]
I have autorank setup with just a simple config for a couple rank promotions
I have the settings.yml set for each server in my network to store the data in a single mysql db.
The database is being populated and has correct times as far as I can tell.

However in game when players use /ar check it is only showing time for that particular server and this also affects the rankups
I would like it to sync with the times in the database so that if a player moves servers their rank follows.
Am I completely missing something here? (Sorry new to this plugin) Or is this intentional

**Comment by Staartvin** [comment]
You should take a look into the global time requirement in the advancedconfig. Simpleconfig doesn't support global time.

**Comment by devryb** [comment]
Ya just noticed this page which I missed.  tyvm :)
https://github.com/Armarr/Autorank-2/wiki/Running-Autorank-in-a-Minecraft-server-network
