### ISSUE TITLE
Autorank Time Error

### ISSUE THREAD

**Issue by xBL0X** [Armarr/Autorank-2#179]
Soa fter name changes, things were going badly with about every plugin but Autorank, it managed to keep data such as played time. But then, a new error came up the other day and many player's playtimes were reset. Mine however, was not. Gives error about UUID fetcher, offline mode, (server is offline mode because BUngeeCord, main server is online mode) and it has worked before which is confusing. Anyway, ways to recreate the error in console is by doing /ar leaderboard force to try and sync the time with player's true palyime. I can supply any and all info needed. Here is console error, Debug is on, also will supply that.
Console: http://pastebin.com/W3rXLKrR
Debug: http://pastebin.com/Cej1wDbe
Thanks,
xBL0X

**Comment by Staartvin** [comment]
I probably know why this error is being produced. I'll fiddle around with som code and come back to you soon.

**Comment by Staartvin** [comment]
Could you download dev version 354 and give me your console output?

**Comment by xBL0X** [comment]
On #354, still gives same error, here is log upon startup with a few commands punched in in-game
Console: http://pastebin.com/ff3eJrcX

**Comment by Staartvin** [comment]
Ah, great, I know what the problem is then. Later today I will put up an updated version on the dev server for you to download.

**Comment by Diggeman** [comment]
What can i do to stop getting Emils as fast anyone has a problem or a question-anwser?

**Comment by Staartvin** [comment]
What do you mean Diggeman?

**Comment by Diggeman** [comment]
I get around 50 messages at least a day. On my mail. I can send a picture If it works here. Wait

**Comment by Diggeman** [comment]
Wait.. So if i unsubscribe i won't get the mails?

**Comment by Staartvin** [comment]
You can change it in your github.com account settings
