### ISSUE TITLE
Autorank says perm file is invalid

### ISSUE THREAD

**Issue by PandahMonium** [Armarr/Autorank-2#185]
![clipboard01](https://cloud.githubusercontent.com/assets/11261373/6433478/f522638a-c035-11e4-9311-c10e6cbaf7eb.jpg)

I keep getting this error within the game. I made sure that the group names are the same within the perm file and the advconfig file for autorank.

here is my perm file:
groups:
  StrangerDanger:
    options:
      add-prefix-suffix: true
      default: 'true'
      build: 'true'
      prefix: '&cStrangerDanger&c '
      rank: '1000'
      rank-ladder: default
      weight: '5'
    permissions:
    - bukkit.command.help
    - bukkit.command.me
    - modifyworld.*
    - minecraft.command.me
    - minecraft.command.help
    - essentials.me
    - essentials.help
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - griefprevention.createclaims
    - essentials.tpa
    - essentials.tpaccept
    - Signshop.DenyLink.Furnace
    - essentials.kit
    - essentials.kits.*
    - essentials.balance
    - essentials.afk
    - essentials.afk.auto
    - essentials.help
    - essentials.mail
    - essentials.mail.send
    - essentials.rules
    - essentials.mute
    - essentials.recipe
    - essentials.nick
    - essentials.back
    - essentials.back.ondeath
    - essentials.keepxp
    - essentials.delhome
    - essentials.delwarp
    - essentials.home
    - essentials.home.bed
    - essentials.tpa
    - essentials.tpdeny
    - essentials.tphere
    - essentials.warp
    - essentials.warp.list
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.spawnmob
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    - randomtp.use.signs
    - essentials.pay
  WellKnown:
    options:
      default: 'false'
      build: 'true'
      prefix: '&9WellKnown&9 '
      rank: '900'
      rank-ladder: default
      weight: '4'
    inheritance:
    - StrangerDanger
    permissions:
    - modifyworld.*
    - essentials.hat
    - essentials.heal
    - echopet.pet.type.creeper
    - essentials.repair
    - essentials.enderchest
    - Signshop.DenyUse.iSell
    - Signshop.DenyUse.iBuy
    - Signshop.Permit
    - Signshop.Signs.Buy
    - Signshop.Signs.Sell
    - essentials.hat
    - essentials.heal
    - essentials.skull
    - essentials.compass
    - essentials.signs.break.buy
    - essentials.signs.break.sell
  CharityGiver:
    options:
      default: 'false'
      build: 'true'
      prefix: '&2CharityGiver&2 '
      rank: '800'
      rank-ladder: default
      weight: '3'
    permissions:
    - modifyworld.*
    - magiccarpet.mc
    - magiccarpet.ml
    - essentials.weather
    - essentials.time
    inheritance:
    - WellKnown
  Invader:
    options:
      default: 'false'
      build: 'true'
      prefix: '&6Invader&6 '
      rank: '700'
      rank-ladder: default
      weight: '2'
    permissions:
    - modifyworld.*
    - essentials.god
    - essentials.repair.all
    - essentials.kick*
    - essentials.ban*
    - essentials.god.pvp
    - griefprevention.restorenature
    - griefprevention.restorenatureaggressive
    - griefprevention.lava
    - griefprevention.adminclaims
    - griefprevention.claimslistother
    - griefprevention.deleteclaims
    - griefprevention.createclaims
    - griefprevention.visualizenearbyclaims
    - griefprevention.eavesdrop
    - griefprevention.overrideclaimc
    - griefprevention.softmute
    - Signshop.SuperAdmin
    - essentials.fly
    - essentials.fly.others
    - essentials.heal.others
    - essentials.workbench
    - essentials.give
    - essentials.exp
    - essentials.exp.give
    - essentials.exp.give.others
    - essentials.exp.others
    - essentials.exp.set
    - essentials.exp.set.others
    - essentials.afk.kickexempt
    - essentials.afk.others
    - essentials.enderchest.*
    - essentials.mute.*
    - essentials.setjail
    - essentials.socialspy.*
    - essentials.spawnmob.*
    - essentials.delhome.others
    - essentials.home.others
    - essentials.sethome
    - essentials.sethome.bed
    - essentials.sethome.multiple
    - essentials.setwarp
    - essentials.tp
    - essentials.tp.others
    - essentials.warp.overwrite.*
    - essentials.chat.spy
    inheritance:
    - CharityGiver
  Illuminati:
    options:
      default: 'false'
      build: true
      prefix: '&5[Illuminati]&5 '
      rank: '600'
      rank-ladder: default
      weight: '1'
    permissions:
    - modifyworld.*
    - griefprevention.ignoreclaims
    - griefprevention.transferclaim
    - griefprevention.adjustclaimblocks
    - essentials.gamemode
    - essentials.gamemode.others
    - essentials.god.others
    - essentials.eco
    - essentials.eco.loan
    - essentials.pay
    - essentials.pay.multiple
    - essentials.sell
    - essentials.setworth
    - essentials.worth
    - essentials.powertool.*
    - essentials.setspawn
    - essentials.spawn.others
    - essentials.warps.*
    - essentials.eco
    inheritance:
    - Invader
schema-version: 1
users:
  6d8c2aec-b1ed-4a6b-b5e0-a92f8eb93542:
    group:
    - Illuminati
    options:
      name: PandahMonium
  707c8362-2405-4444-ad41-fbaead04497e:
    options:
      name: SnickelFritz420
    group:
    - Illuminati

and my advconfig file:
#############################################################################
#                                                                           #
#                   Autorank 2 Advanced Config                              #
#                                                                           #
#   Please use the SimpleConfig unless you know what you are doing and      #
#   need functionality that the SimpleConfig doesn't provide.               #
#                                                                           #
#############################################################################

ranks:
    StrangerDanger:
        requirements:
            money:
                value: 100000
        results:
            rank change: StrangerDanger;Wellknown
            command: 'say &p just got a promotion; broadcast &p has just been promoted to a WellKnown player!; give &p 314 1; give &p 315 1; give &p 316 1; give &p 317 1; give &p 357 1'
            message: 'Congratulations, you are now a WellKnown player. Have a cookie!!! And have a nice day.'
    Wellknown:
        requirements:
            time:
                value: 5d
        results:
            rank change: WellKnown;CharityGiver
            command: 'say &p has just been promoted to CharityGiver!; give &p 310 1; give &p 311 1; give &p 312 1; give &p 313 1; give &p 392 1; give &p 354 1'
            message: 'Congratulations, you are now a CharityGiver. Have a potato...... and a piece of cake.'

**Comment by PandahMonium** [comment]
Also, is there a way for autorank to work when some one donates through buycraft?

**Comment by Staartvin** [comment]
Could you use pastebin.co for your config?

I'm not sure how you want buycraft to work with Autorank. Would you like an 'amount donated' requirement?

**Comment by PandahMonium** [comment]
http://pastebin.com/W1ysuHM4
http://pastebin.com/vhrZHgMq

And yes, with buycraft. $10 min to rank up.

**Comment by Staartvin** [comment]
I'm not sure if I can do the buycraft thing, but I'll look into it.

Your 'WellKnown' group is spelled with a capital K. In the Autorank config you spelled it with a lower 'k'.

**Comment by PandahMonium** [comment]
Ok, thank you.
