### ISSUE TITLE
Autorank not tracking time

### ISSUE THREAD

**Issue by TVDAKKER** [Armarr/Autorank-2#186]
Hello!
i installed autorank a few hours ago on a server i have console acces to (this is a voltz server running MCPC+) i had no problems setting all the ranks and stuff allthough when i had everything set up autorank wasnt tracking the time players were playing.... if someone could plz help me with this that would be nice

**Comment by Staartvin** [comment]
Any error logs or debug logs?

**Comment by Staartvin** [comment]
Closed due to inactivity.
