### ISSUE TITLE
Error occurred while enabling Autorank v3.4 (Is it up to date?)

### ISSUE THREAD

**Issue by BlueSoapTurtle** [Armarr/Autorank-2#187]
Trying to add some stat requirements from lolmewnstats.
Advanced config(check the part with the Hero): http://hastebin.com/ufemedemiq.yml
settings.yml: http://hastebin.com/veqoyoxuwi.yml
Error log (just the part about autorank): http://hastebin.com/loceseciqe.log

Using the latest version from the spigot page. maybe I should use the dev build?

Edit1: Used the dev build, still didn't work. moved back to 3.4.

**Comment by Staartvin** [comment]
Just a few notes:

- The hero group has a rank change with a typo. It must be 'hero', not 'here'.
- eggs thrown is not a valid requirement. A list of requirements can be found here: https://github.com/Armarr/Autorank-2/blob/master/AdvancedConfig.yml

I'll manually add requirements over time.

Also, make sure to stay on the dev version. 3.4 has some nasty bugs in it.

**Comment by BlueSoapTurtle** [comment]
alright. Fixed the 'here' to 'hero'
"
# new requirements and results can be added by other plugins that hook into the Autorank API
# these are the ones that are included in the main plugin:
"

I thought it would be possible for me to add requirements from the stats plugin?

**Comment by Staartvin** [comment]
Yes, but Autorank does not support all Stats requirements automatically. The sentence you quote is meant to be read by developers. They can make custom plugins that allow you, as a user/admin, to add extra requirements. I will however add the eggs thrown requirement for you ;)

**Comment by BlueSoapTurtle** [comment]
oh. alright, makes sense now :)
how difficult would it be to implement some more of the stats?
eggs thrown, tools broken, arrows shot, food eaten(omnomnom), deaths, bedenter bucketfill
Made 35 ranks for my server with these as extra requirements to make it harder to rankup.
Really thankful for you making the plugin, it's a great feature to have on any server. You should make a paid version with tons of more requirements or something :+1:
