### ISSUE TITLE
Autorank warning

### ISSUE THREAD

**Issue by RobinTR** [Armarr/Autorank-2#188]
My spigot version: 1649
Plugin version: http://62.131.38.74:8080/job/Autorank/320/

 [Thread-25/INFO]: [Autorank] Could not find name of account with uuid: 'b0637227-38ba-3407-8ff6-8e26404c95ad'
 [Thread-25/WARN]: Unexpected token END OF FILE at position 0.
 [Thread-25/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
 [Thread-25/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
 [Thread-25/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
 [Thread-25/WARN]: 	at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
 [Thread-25/WARN]: 	at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
 [Thread-25/WARN]: 	at java.lang.Thread.run(Unknown Source)
 [Thread-26/INFO]: [Autorank] Could not find name of account with uuid: 'fdc961a5-9a98-32a9-b5d6-cbf0e02ce0ff'
 [Thread-26/WARN]: Unexpected token END OF FILE at position 0.
 [Thread-26/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
 [Thread-26/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
 [Thread-26/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
 [Thread-26/WARN]: 	at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
 [Thread-26/WARN]: 	at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
 [Thread-26/WARN]: 	at java.lang.Thread.run(Unknown Source)
 [Thread-27/INFO]: [Autorank] Could not find name of account with uuid: 'ff9db988-fa98-3a68-bad5-d16836d50417'
 [Thread-27/WARN]: Unexpected token END OF FILE at position 0.
 [Thread-27/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
 [Thread-27/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
 [Thread-27/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
 [Thread-27/WARN]: 	at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
 [Thread-27/WARN]: 	at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
 [Thread-27/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Staartvin** [comment]
You should update to dev build 356 and let Autorank regenerate your data.yml. Backup your old data file beforehand.

**Comment by carelli99** [comment]
i have same error, with Spigot 1.8.7, what can i do?
