### ISSUE TITLE
Unknown error in Advanced Config. (NullPointerException)

### ISSUE THREAD

**Issue by Minuhmize** [Armarr/Autorank-2#189]
I'm getting an unknown error in my console when it tries to enable Autorank. Here is a picture of the error message: http://gyazo.com/57629fd4c92ee25160268ec0c930778c

If needed, here is my config: https://www.dropbox.com/s/p88hmdcbf0h6zf9/AdvancedConfig.yml?dl=0

Thanks!

**Comment by Minuhmize** [comment]
Also, just so you know I'm not some annoying 12 year old who can't solve their own problem, I know that a Null Pointer Exception means there's something (a character, number, symbol, etc.) in the config that is messing it up. The thing is, I have searched and searched the config many times and I can't find the issue. I know that I can't use indentations because YAML doesn't read those but that shouldn't be an issue because my notepad++ is set to replace them with spaces. So yea... IDK MAN!

**Comment by Staartvin** [comment]
Don't worry about your 'showness' of age. I don't mind any youngster as long as they're a bit relaxed. This error means one of the groups doesn't have the proper requirements set up. You should update to dev build 356 and remove the 'Royal' group altogether.

**Comment by Staartvin** [comment]
Closed due to inactivity.
