### ISSUE TITLE
Permissions group 'guest' should be 'Guest'

### ISSUE THREAD

**Issue by OlleyGibson** [Armarr/Autorank-2#192]
I have just made new Ranks and linked them to the GroupManager Config, and in-game it says Permissions group 'guest' should be 'Guest',
Here is my AdvancedConfig in AutoRank:

ranks:
    guest:
        requirements:
            time:
                value: 8h
        results:
            rank change: guest;citizen
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Citizen!'
            message: 'Congratulations, you are now a Citizen.'
    citizen:
        requirements:
            time:
                value: 30h
        results:
            rank change: citizen;trusted
            command: 'say &p has just been promoted to Trusted!'
            message: 'Congratulations, you are now a Trusted.'

**Comment by OlleyGibson** [comment]
Here is the GroupManager Permissions/Groups:

groups:
  Guest:
    default: true
    permissions:
    - essentials.suicide
    - essentials.spawn
    - essentials.afk
    - essentials.motd
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.tpdeny
    - essentials.mail
    - essentials.warp
    - essentials.warplist
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.sell
    - essentials.worth
    - essentials.sellhand
    - essentials.afk
    - essentials.help
    - essentials.helpop
    - essentials.mail
    - essentials.me
    - essentials.msg
    - essentials.rules
    - essentials.back
    - essentials.sethome
    - essentials.deletehome
    - essentials.home
    - essentials.spawn
    - essentials.recipe
    - kits.spawn.guest
    inheritance:
    info:
      prefix: '&f[&7Guest&f]&7'
      build: false
      suffix: ''
  Citizen:
    default: false
    permissions:
    - essentials.tpa
    - essentials.worth
    - essentials.warp
    - essentials.warp.list
    - essentials.pay
    - essentials.balance
    - essentials.balancetop
    - essentials.ping
    - essentials.msg
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.home
    - essentials.me
    - essentials.mail
    - essentials.mail.send
    - essentials.kit
    - essentials.exp
    - essentials.feed
    - essentials.hat
    - essentials.kit
    - essentials.kits
    - essentials.workbench
    - essentials.list
    - essentials.nick
    - essentials.enderchest
    - essentials.recipe
    - essentials.top
    - kits.list
    inheritance:
    - Guest
    info:
      prefix: '&f[&eCitizen&f]&e'
      build: true
      suffix: ''

**Comment by Staartvin** [comment]
Could you repost them in pastebin and give the link? This is a bit unreadable.

**Comment by Staartvin** [comment]
Closed due to inactivity.
