### ISSUE TITLE
Plugin overwriting other plugin prefixes

### ISSUE THREAD

**Issue by MrProtagonist** [Armarr/Autorank-2#195]
Hello. I use Autorank only for the first level on my server, as I wanted it to be based on McMMO lvl, time played, and the world they were in. It works great, and I have another ranking system in place for the remaining ranks, but it seems that Autorank is overwriting GroupManager and SimpleSuffix prefixes.

I believe this because when I do /ar check to anybody affected, it says they are at "Rookie" and have no more levels to go (rookie is the tag they are getting). Setting a prefix with essentials, group manager, or simplesuffix doesn't help my issue.

**Comment by Staartvin** [comment]
Can I see your config?

**Comment by Staartvin** [comment]
Closed due to inactivity.
