### ISSUE TITLE
Server network - time not sync'ing for one player?

### ISSUE THREAD

**Issue by TheLecturer** [Armarr/Autorank-2#196]
Hi,

I had a user complain that they hadn't ranked up, even though had played sufficient time for the next rank. Wondering if you can help work out where the problem lies?

Multi-server Bungeecord network.  Rank up is based on time played, using advanced config and the "global time" requirement.

mySQL db value of "time" is 15540.
"MAIN" server, Data.yml = 25010.
"CREATIVE" server, Data.yml = 1500.
"EXTRAHARD" server, Data.yml = 655.
"GAMES" server, Data.yml = 100.
"LOBBY" server, Data.yml = 905.
"PLOTS" server, Data.yml = 3390.
"SUPPLY" server, Data.yml = 5500.

My simple understanding was that the value in the mySQL db should be a sum of all the individual servers...?  If that is the case, then the mySQL db value should be 37060. But maybe I am misunderstanding how things work.

Using Autorank version 3.1-Dev-227 on CraftBukkit version git-Spigot-1627 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT).

Many thanks for any insight you can give.

**Comment by Staartvin** [comment]
As you have many servers connected to the same database, it could be that at one point of connecting a server, you forgot to do /ar sync. That's no problem though. You should stop all the servers, change the time to what it should be in the MySQL database, and start everything back up again. That should do the trick!

**Comment by Staartvin** [comment]
Closed due to inactivity.
