### ISSUE TITLE
Double rank up

### ISSUE THREAD

**Issue by StillSwingin** [Armarr/Autorank-2#197]
Hi,

First of all, I'm using Spigot 1.8 and Autorank-3.5.1-Dev-368. 

I have the plugin configured so players rank up depending on the playtime. It usually works correctly, except for two players (by now) that entered the server as guests, and when they played enough time, they got ranked instead of one level on the permission groups, two levels, although they didn't have the amount of time required for that second level.

Why would this happen? 

Thank you

**Comment by Staartvin** [comment]
Could you show me your config (via pastebin) please?

**Comment by StillSwingin** [comment]
Settings: http://pastebin.com/ECbWc9bS
Advanced config: http://pastebin.com/C8D88vfx

**Comment by Staartvin** [comment]
Does any rank have the error, or only a specific rank?

**Comment by StillSwingin** [comment]
Forastero to Campesino, and Campesino to Aprendiz

**Comment by Staartvin** [comment]
What does the player see when he does /ar check?

**Comment by StillSwingin** [comment]
any player?

**Comment by Staartvin** [comment]
The player or players that are experiencing the bug.

**Comment by Staartvin** [comment]
Closed due to inactivity.
