### ISSUE TITLE
AutoRank not identifying my permissions 

### ISSUE THREAD

**Issue by Chaise91** [Armarr/Autorank-2#198]
I'll begin by saying I believe this pay be a PEX issue however AutoRank is the plugin throwing warnings at me so I figure I'd start here.

Log: http://pastebin.com/iEyufLkk

As you may expect I do have a seemingly valid permissions file which I recently set PEX up to use MySQL as a back end - which is the exact time AutoRank was unable to find said groups. Upon joining the server, it has my prefix as default and a message pops up every minute or so that says: "<AUTORANK> Warning: Permissions group is not defined: 'RainBows'

AutoRank settings folder: http://pastebin.com/mr8yPDZJ

PEX config folder: http://pastebin.com/6amXPF6m

AutoRank SimpleConfig: http://pastebin.com/7MV7b1RR

I'm thinking this is a MySQL issue however I can't seem to figure out why...

**Comment by Staartvin** [comment]
Could you update to Autorank 3.5.1 first and see if this fixes anything?

**Comment by Staartvin** [comment]
Closed due to inactivity.
