### ISSUE TITLE
autorank is disabled check your server.log

### ISSUE THREAD

**Issue by datzijnpasgamez** [Armarr/Autorank-2#199]
autorank is disabled check your server.log
and there is an error and called
Could not found expected ''
  in 'string', line 54, column 23:
                 command, "say & p You get a promotion; b ...
what should I do with it

**Comment by datzijnpasgamez** [comment]
This server is tomorrow on

**Comment by Staartvin** [comment]
Could you post your config via pastebin?

**Comment by Staartvin** [comment]
Closed due to inactivity.
