### ISSUE TITLE
Indent

### ISSUE THREAD

**Issue by Bammerbom** [Armarr/Autorank-2#205]
Why does autorank have 8 spaces indent?

Java's standard is 4, sometimes 2 is used, but 8 is a lot.

I would recommend running a reformat on your project.

**Comment by Staartvin** [comment]
Autorank just uses 4, if you're talking about the AdvancedConfig/SimpleConfig.

**Comment by Bammerbom** [comment]
I am talking about the code.
And I just realised it is 1 tab, and not 8 spaces. but it looks like 8 spaces.

**Comment by Staartvin** [comment]
Ah, that's the default setting of Eclipse. Don't worry about it ;)

**Comment by Bammerbom** [comment]
In netbeans it looks really weird, and it makes editing your code almost impossible.
