### ISSUE TITLE
Autorank is Disabled. Check your server.log

### ISSUE THREAD

**Issue by Master1122334455** [Armarr/Autorank-2#206]
On my server Autorank is disabled and I have looked through the logs but it shows me nothing or at least nothing I understand... Please help...

**Comment by Master1122334455** [comment]
Plus it was working fine and then suddenly stopped working... I am guessing it could be an outdated plugin?

**Comment by Master1122334455** [comment]
Spigot 1.7.10 btw

**Comment by Staartvin** [comment]
What version of Autorank are you running? Can you show your server log for when you start the server?

**Comment by Master1122334455** [comment]
A bit late on the reply... It was stats that was causing it, I just converted the MySQL info over to the Autorank setting and then deleted stats and it fixed the whole problems

**Comment by Staartvin** [comment]
Ah, sorry, for that. Good you fixed it yourself!
