### ISSUE TITLE
Stats is not connecting to AutoRank. 

### ISSUE THREAD

**Issue by Hardcore0uch** [Armarr/Autorank-2#216]
Here is our console

Stats is working but auto ranks doesn't recognise it. When we do /ar hooks it doesn't show up.

How do we fix this?

22.04 21:54:22 [Server] WARN DEV versions are not guaranteed to be stable and generally shouldn't be used on big production servers with lots of players.
22.04 21:54:22 [Server] WARN You're running a DEV version, be sure to backup your Autorank folder!
22.04 21:54:22 [Server] INFO Autorank 3.5.1-Dev-374 has been enabled!
22.04 21:54:22 [Server] INFO Using timings of: stats
22.04 21:54:22 [Server] INFO Language file loaded (lang.yml)
22.04 21:54:22 [Server] INFO Data file loaded
22.04 21:54:22 [Server] INFO Interval check every 5 minutes.
22.04 21:54:22 [Server] INFO Loaded libraries and dependencies
22.04 21:54:22 [Server] INFO Couldn't hook into Stats! Make sure the version is correct and Stats properly connects to your MySQL database.
22.04 21:54:22 [Server] INFO Stats (by Lolmewn) is not enabled!
22.04 21:54:22 [Server] INFO Found Stats plugin: Stats (by Lolmewn)
22.04 21:54:22 [Server] INFO Could not find Stats because it's probably disabled! Does Stats properly connect to your MySQL database?
22.04 21:54:22 [Server] INFO Successfully established connection to localhost:3306
22.04 21:54:22 [Server] INFO Loaded playerdata.
22.04 21:54:22 [Server] INFO Loaded stored uuids.
22.04 21:54:22 [Server] INFO Settings config file loaded
22.04 21:54:22 [Server] INFO Advanced config file loaded
22.04 21:54:22 [Server] INFO Simple config file loaded
22.04 21:54:22 [Server] INFO Enabling Autorank v3.5.1-Dev-374
22.04 21:54:22 [Server] INFO Version 2.0.0-SNAPSHOT-186 enabled!
22.04 21:54:22 [Server] INFO Enabling Stats v2.0.0-SNAPSHOT-186
22.04 21:54:22 [Server] INFO [Vault][Chat] PermissionsEx_Chat hooked.
22.04 21:54:22 [Server] INFO [Vault][Permission] PermissionsEx hooked.
22.04 21:54:22 [Server] INFO Permissions file successfully reloaded
22.04 21:54:22 [Server] INFO Initializing file backend
22.04 21:54:22 [Server] INFO Enabling PermissionsEx v1.23.2

**Comment by Staartvin** [comment]
Does Stats properly connect to the mysql database? Can you show me your whole server log?

**Comment by Hardcore0uch** [comment]
24.04 22:25:28 [Server] INFO Config files have been correctly setup!
24.04 22:25:09 [Server] INFO No new version available
24.04 22:25:08 [Server] INFO Checking for Updates ... 
24.04 22:25:08 [Server] INFO Making a backup of data.yml and playerdata.yml..
24.04 22:25:08 [Server] Startup Done (2.331s)! For help, type "help" or "?"
24.04 22:25:08 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
24.04 22:25:08 [Server] WARN DEV versions are not guaranteed to be stable and generally shouldn't be used on big production servers with lots of players.
24.04 22:25:08 [Server] WARN You're running a DEV version, be sure to backup your Autorank folder!
24.04 22:25:08 [Server] INFO Autorank 3.5.1-Dev-374 has been enabled!
24.04 22:25:08 [Server] INFO Using timings of: stats
24.04 22:25:08 [Server] INFO Language file loaded (lang.yml)
24.04 22:25:08 [Server] INFO Data file loaded
24.04 22:25:08 [Server] INFO Interval check every 5 minutes.
24.04 22:25:08 [Server] INFO Loaded libraries and dependencies
24.04 22:25:08 [Server] INFO Couldn't hook into Stats! Make sure the version is correct and Stats properly connects to your MySQL database.
24.04 22:25:08 [Server] INFO Stats (by Lolmewn) is not enabled!
24.04 22:25:08 [Server] INFO Found Stats plugin: Stats (by Lolmewn)
24.04 22:25:08 [Server] INFO Could not find Stats because it's probably disabled! Does Stats properly connect to your MySQL database?
24.04 22:25:08 [Server] INFO Successfully established connection to localhost:3306
24.04 22:25:08 [Server] INFO Loaded playerdata.
24.04 22:25:08 [Server] INFO Loaded stored uuids.
24.04 22:25:08 [Server] INFO Settings config file loaded
24.04 22:25:08 [Server] INFO Advanced config file loaded
24.04 22:25:08 [Server] INFO Simple config file loaded
24.04 22:25:08 [Server] INFO Enabling Autorank v3.5.1-Dev-374
24.04 22:25:08 [Server] INFO Version 2.0.1-272 enabled!
24.04 22:25:08 [Server] INFO Using UUID for Player management
24.04 22:25:08 [Server] INFO Enabling Stats v2.0.1-272
24.04 22:25:08 [Server] INFO [Vault][Chat] PermissionsEx_Chat hooked.
24.04 22:25:08 [Server] INFO [Vault][Permission] PermissionsEx hooked.
24.04 22:25:07 [Server] INFO Permissions file successfully reloaded
24.04 22:25:07 [Server] INFO Initializing file backend
24.04 22:25:07 [Server] INFO Enabling PermissionsEx v1.23.2
24.04 22:25:07 [Server] INFO Preparing start region for level 2 (Seed: -7398725068896310206)
24.04 22:25:07 [Multicraft] Skipped 77 lines due to rate limit (30/s)
24.04 22:25:06 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
24.04 22:25:06 [Server] INFO Max TNT Explosions: 100
24.04 22:25:06 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
24.04 22:25:06 [Server] INFO Max Entity Collisions: 8
24.04 22:25:06 [Server] INFO Sending up to 10 chunks per packet
24.04 22:25:06 [Server] INFO Structure Info Saving: true
24.04 22:25:06 [Server] INFO Random Lighting Updates: false
24.04 22:25:06 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
24.04 22:25:06 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
24.04 22:25:06 [Server] INFO Entity Activation Range: An 32 / Mo 48 / Mi 16
24.04 22:25:06 [Server] INFO Wheat Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Sapling Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Pumpkin Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Mushroom Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Melon Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Cane Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Cactus Growth Modifier: 100%
24.04 22:25:06 [Server] INFO Nerfing mobs spawned from spawners: false
24.04 22:25:06 [Server] INFO Replace Blocks: [1, 5]
24.04 22:25:06 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
24.04 22:25:06 [Server] INFO Engine Mode: 1
24.04 22:25:06 [Server] INFO Anti X-Ray: true
24.04 22:25:06 [Server] INFO Mob Spawn Range: 12
24.04 22:25:06 [Server] INFO -------- World Settings For [New World---] --------
24.04 22:25:06 [Server] INFO Preparing level "New World---"
24.04 22:25:06 [Server] INFO  Beginning UUID conversion, this may take A LONG time 
24.04 22:25:06 [Server] INFO Enabled Version 1.5.3-b37
24.04 22:25:06 [Server] INFO [Chat] PermissionsEx found: Waiting
24.04 22:25:06 [Server] INFO [Permission] SuperPermissions loaded as backup permission system.
24.04 22:25:06 [Server] INFO [Permission] PermissionsEx found: Waiting
24.04 22:25:06 [Server] INFO Enabling Vault v1.5.3-b37
24.04 22:25:06 [Server] INFO Loading Autorank v3.5.1-Dev-374
24.04 22:25:06 [Server] INFO Loading Vault v1.5.3-b37
24.04 22:25:06 [Server] INFO Loading Stats v2.0.1-272
24.04 22:25:06 [Server] INFO Loading PermissionsEx v1.23.2
24.04 22:25:06 [Server] INFO Set PluginClassLoader as parallel capable
24.04 22:25:06 [Server] INFO Using epoll channel type
24.04 22:25:05 [Server] INFO Starting Minecraft server on 5.196.90.55:25586
24.04 22:25:05 [Server] INFO Generating keypair
24.04 22:25:05 [Server] INFO Debug logging is disabled
24.04 22:25:05 [Server] INFO Using 4 threads for Netty based IO
24.04 22:25:05 [Server] INFO Server Ping Player Sample Count: 12
24.04 22:25:05 [Server] INFO This server is running CraftBukkit version git-Spigot-dbe012b-63e28b1 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
24.04 22:25:05 [Server] INFO Default game type: CREATIVE
24.04 22:25:05 [Server] INFO Loading properties
24.04 22:25:05 [Server] INFO Starting minecraft server version 1.8.3
24.04 22:25:01 [Server] INFO Loading libraries, please wait...
24.04 22:25:01 [Multicraft] Loaded config for "Spigot (1.8.3 R0.1 BuildTools: 35) !!!Might break plugins if coming from 1.8!!!"
24.04 22:25:01 [Multicraft] Starting server!
24.04 22:25:01 [Multicraft] Loading server properties

**Comment by Hardcore0uch** [comment]
stats created the tables called Stats_block, Stats_death etc. in the sql. thus it is connected and autorank created the autorank table in the sql

**Comment by Staartvin** [comment]
Ah, you are using Stats 2, the dev version needs Stats 3.0

**Comment by Hardcore0uch** [comment]
Oh, where can i find Stats 3.0 ?

**Comment by Staartvin** [comment]
http://dev.bukkit.org/bukkit-plugins/lolmewnstats/

**Comment by Hardcore0uch** [comment]
We have downloaded and put on the file. Still having problems

27.04 12:29:33 [Server] INFO Saved the world
27.04 12:29:33 [Server] INFO Saving...
27.04 12:29:33 [Server] INFO Saving is already turned on.
27.04 12:29:33 [Multicraft] Auto-saving world...
27.04 12:19:27 [Server] INFO Saved the world
27.04 12:19:27 [Server] INFO Saving...
27.04 12:19:27 [Server] INFO Saving is already turned on.
27.04 12:19:27 [Multicraft] Auto-saving world...
27.04 12:10:02 [Server] WARN Couldn't connect to global server! Maybe it's offline...
27.04 12:09:47 [Server] INFO Config files have been correctly setup!
27.04 12:09:28 [Server] INFO No new version available
27.04 12:09:27 [Server] INFO Checking for Updates ... 
27.04 12:09:27 [Server] INFO Making a backup of data.yml and playerdata.yml..
27.04 12:09:27 [Server] Startup Done (1.871s)! For help, type "help" or "?"
27.04 12:09:27 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
27.04 12:09:27 [Server] WARN DEV versions are not guaranteed to be stable and generally shouldn't be used on big production servers with lots of players.
27.04 12:09:27 [Server] WARN You're running a DEV version, be sure to backup your Autorank folder!
27.04 12:09:27 [Server] INFO Autorank 3.5.1-Dev-374 has been enabled!
27.04 12:09:27 [Server] INFO Using timings of: stats
27.04 12:09:27 [Server] INFO Language file loaded (lang.yml)
27.04 12:09:27 [Server] INFO Data file loaded
27.04 12:09:27 [Server] INFO Interval check every 5 minutes.
27.04 12:09:27 [Server] INFO Loaded libraries and dependencies
27.04 12:09:27 [Server] INFO Couldn't hook into Stats! Make sure the version is correct and Stats properly connects to your MySQL database.
27.04 12:09:27 [Server] INFO Stats (by Lolmewn) is not enabled!
27.04 12:09:27 [Server] INFO Found Stats plugin: Stats (by Lolmewn)
27.04 12:09:27 [Server] INFO Could not find Stats because it's probably disabled! Does Stats properly connect to your MySQL database?
27.04 12:09:27 [Server] INFO Successfully established connection to localhost:3306
27.04 12:09:27 [Server] INFO Loaded playerdata.
27.04 12:09:27 [Server] INFO Loaded stored uuids.
27.04 12:09:27 [Server] INFO Settings config file loaded
27.04 12:09:27 [Server] INFO Advanced config file loaded
27.04 12:09:27 [Server] INFO Simple config file loaded
27.04 12:09:27 [Server] INFO Enabling Autorank v3.5.1-Dev-374
27.04 12:09:27 [Server] INFO Version 2.0.2-SNAPSHOT-277 enabled!
27.04 12:09:27 [Server] INFO Using UUID for Player management
27.04 12:09:27 [Server] INFO Enabling Stats v2.0.2-SNAPSHOT-277
27.04 12:09:27 [Server] INFO [Vault][Chat] PermissionsEx_Chat hooked.
27.04 12:09:27 [Server] INFO [Vault][Permission] PermissionsEx hooked.

**Comment by Staartvin** [comment]
You still got version '2.0.2-SNAPSHOT-277'. You need this one: http://dev.bukkit.org/bukkit-plugins/lolmewnstats/files/64-stats-v3-0-0-dev/

**Comment by Hardcore0uch** [comment]
Hey, Thanks for your help. Managed to get it to work. 

Another problem. Do you know how to make it where 

once a person has achieved all the /ar check The Rank goes on his suffix. Do we require colorme , ChatManager?

Ive been doing commands at the end in command: stating /suffix @p Rank1 but its just not working

**Comment by MedicinalSnacks** [comment]
Post your advanced config file so we can see? The string above: `/suffix @p Rank1` is incorrect. The placeholder for a playername is `&p` and because commands fire from console you need to remove the `/` in front of your command. A fixed string (assuming /suffix is actually a command on your server) would be: `command: 'suffix &p Rank1'`

**Comment by Staartvin** [comment]
Closed due to inactivity.
