### ISSUE TITLE
Promoting every update interval

### ISSUE THREAD

**Issue by MedicinalSnacks** [Armarr/Autorank-2#217]
Hello,

First of all I'd like to thank you for taking the time to read and (hopefully!) help me with my issue. I've run into a bug where AutoRank likes to promote somebody every time the plugin is set to update. Below, I will attach my advanced config, settings, and permissions file so you know exactly what I am trying to do. I use PEX, and the latest dev build of AutoRank, although I have tried the most recent bukkit approved build as well, to no avail.

I think the issue stems from AR checking groups and using getplayergroups() instead of getprimarygroup() as discussed in https://github.com/Armarr/Autorank-2/issues/24. Vault is returning all the groups the player belongs to, thinks its time to promote, and wildly promotes and demotes people every update-interval (set in the settings file).

Advanced Config: http://pastebin.com/MK3yRB5k
Settings: http://pastebin.com/ZSGnHihQ
Permissions (PEX): http://pastebin.com/1KvYVQdF

Please help me! I really want automatic time based ranks. I've used this plugin and had awesome success but it seems something has gone terribly wrong after the 1.8 update.

**Comment by Staartvin** [comment]
What version of Autorank are you using?

**Comment by cooperisdunn** [comment]
My problem persists when using the latest bukkit approved build, and the latest dev builds.

**Comment by cooperisdunn** [comment]
Uh Just a heads up, this is OP, MedicinalSnacks.

**Comment by cooperisdunn** [comment]
Any support on this issue would be greatly appreciated...

**Comment by cooperisdunn** [comment]
My players and I are dying for automatic time-based ranks

**Comment by Staartvin** [comment]
Are you still having the same problems? Or only the 'killing on automatic ranks'?

**Comment by cooperisdunn** [comment]
Yes I am still having the same problems.

**Comment by Staartvin** [comment]
Instead of using the command to rank up, could you use Autoranks built-in rank change and see if that changes anything?

**Comment by cooperisdunn** [comment]
Yes, I can. Should I use the latest dev build or the latest build you have
promoted on devbukkit?

**Comment by Staartvin** [comment]
Uhm, try to use the latest dev version 381.

**Comment by cooperisdunn** [comment]
Okay, will do.

**Comment by Staartvin** [comment]
Closed due to inactivity.
