### ISSUE TITLE
Update for Stats v3

### ISSUE THREAD

**Issue by SXRWahrheit** [Armarr/Autorank-2#218]
Currently doesn't hook properly. Can pull a relevant error if needed.

**Comment by Staartvin** [comment]
Could you provide the build number of Stats and Autorank as well as the error occuring?

**Comment by kz5ee** [comment]
I'm using build #352 of Stats, and v3.5.1 of Autorank.  I'm getting this on startup:  http://pastebin.com/nSLtmB3E

**Comment by SXRWahrheit** [comment]
Stats build #353 gives this error on AutoRank load:

http://pastebin.com/g4i7h8T3

Sorry for the delay - life got busy.

**Comment by SXRWahrheit** [comment]
http://ci.centrility.nl/job/Stats/353/

**Comment by Staartvin** [comment]
Autorank 3.5.1 only supports Stats 2.0.1. That's why you are getting the error. The latest dev builds of Autorank DO support Stats 3 though ;)

**Comment by SXRWahrheit** [comment]
Latest build fine, or do you have a recommended build number?

**Comment by Staartvin** [comment]
Closed due to inactivity.
