### ISSUE TITLE
An internal error occurred when doing '/ar check' due to the mobs killed requirement

### ISSUE THREAD

**Issue by AJKproductions** [Armarr/Autorank-2#219]
Hello, i have recently installed Auto Rank onto my server and it use to work. However when i added the 'mobs killed' requirement, it kept giving me an internal error message. Here is the log from the server:
http://pastebin.com/pEh4Tu5f

And my config file:
http://pastebin.com/ns3i00g6
any help?

**Comment by cooperisdunn** [comment]
My guess would be to try updating to stats 3.0

http://dev.bukkit.org/bukkit-plugins/lolmewnstats/

**Comment by AJKproductions** [comment]
Tried updating, but then Auto rank stopped loading and said that it couldn't find the main class file in the stats plugin. So i down graded. (I downgraded to the latest Stats 2.0 build)

**Comment by Staartvin** [comment]
What version of Autorank & Stats are you currently running?

**Comment by Staartvin** [comment]
Closed due to inactivity.
