### ISSUE TITLE
'There is invalid groups defined in your config' 

### ISSUE THREAD

**Issue by AJKproductions** [Armarr/Autorank-2#222]
Having a problem,
Auto rank puts this in the console when i load up my server:

[Server thread/ERROR]: [Autorank] There are invalid groups defined in the config!
[Server thread/ERROR]: [Autorank] Check your config!

I have checked the config over and over again, but i can't see any problems with it. However I have done some testing and i have found that the two groups in the Advanced Config (Red & Blue)  seem to be causing this. I have no idea why, here is the links to the Advanced config, the debugger thing and the list of plugins used:

Advanced Config: http://pastebin.com/4iguQUvY

The debugger file: http://pastebin.com/qAw2YPXP

Here is the reinvent plugins :
Essentials, Hero chat, PermissionsEx, Enjin Minecraft Plugin 

Any help would be much appreciated. :smile:

**Comment by Mike7493** [comment]
I am having this same problem with no idea why.

**Comment by Staartvin** [comment]
Blue and Red both have rank changes that are invalid.

**Comment by AJKproductions** [comment]
But all the ranks Red & Blue (& Gray) are defined correctly in PermissionsEX? And all the groups work correctly too...

**Comment by Staartvin** [comment]
The rank change of rank 'Blue' is Gray;Blue, this is not correct. This would mean that a player from Gray gets ranked up to Blue, but that is not possible in the Blue rank. It should be 'Blue;otherrank'. The same applies for the Red rank.

**Comment by martinambrus** [comment]
I'm actually having the exact same issue by simply using the default config.

**Comment by martinambrus** [comment]
Ah, ignore my last comment. It was due to incorrect group names in the PEX database..

**Comment by Staartvin** [comment]
Closed due to inactivity.
