### ISSUE TITLE
/ar leaderboard throws CME

### ISSUE THREAD

**Issue by TNTUP** [Armarr/Autorank-2#225]
Typing /ar leaderboard throws a CME, http://pastebin.com/pr34N6Ag

Could it be related to lolmewnstats? I see it in the stacktrace, so either its their issue than AR? How I can disable leaderboard? I couldn't find in the config

EDIT: I'm suspecting that I have invalid UUIDs in the playerdata/uuids folder, how I can find those invalid UUIDs? Could AR autoremoving the invalid ones?

**Comment by Staartvin** [comment]
Hmm, this is quite odd. Stats shouldn't give this error when you do /ar leaderboard. What version of Autorank do you have?

**Comment by TNTUP** [comment]
Using AR 3.4 on Spigot 1.8.6, I'm using this version of AR due to rankup issues

**Comment by Staartvin** [comment]
Could you use the latest dev build? #381?

**Comment by Staartvin** [comment]
Closed due to inactivity.

**Comment by TNTUP** [comment]
Sorry for the inactivity, I didn't got the email when you answered since Jun 6, I can't update AR because you're supporting Stats 3 which I'm on Stats 2.
