### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SteveTheDog** [Armarr/Autorank-2#227]
Server crashes due to an Autorank memory leak.
Log from crash: http://pastebin.com/zc86uXCr
crash report found in crash-reports folder: http://pastebin.com/0N33hBGC
AutoRank version: 3.5.1

**Comment by Staartvin** [comment]
When is this error happening?

**Comment by 9190281** [comment]
At least once every day... been happening for months now.

**Comment by 9190281** [comment]
Is there any update on this issue?

**Comment by Staartvin** [comment]
Sorry for the lack of responses. How many GBs did you locate to your server?

**Comment by 9190281** [comment]
12GB.

**Comment by Staartvin** [comment]
Okay, so that's plenty of RAM. How long does your server stay on for in one run?

**Comment by 9190281** [comment]
24 hours.  I've also got some more information on this issue; I've been running Autorank on only flatfile and not mysql for about 4 days now, and have gotten no crashes.  It seemed to be that Autorank was opening up a crap ton of mysql connections or something, causing my other servers on the same dedi to also crash.

**Comment by Staartvin** [comment]
Closed due to inactivity.
