### ISSUE TITLE
Autorank v3.5.1 Frozen Times

### ISSUE THREAD

**Issue by PneumaticHeal** [Armarr/Autorank-2#228]
It seems using AR v3.5.1 some players are experiencing frozen playtimes that refuse to update. I have tried even updating to the latest dev-branch of 381 but have had no luck. Some players are experiencing this issue while most players have no problem. I have tried forcechecking the users and setting their time to 0 and resetting their time back to what it was to see if it would continue from there but still no luck.

**Comment by Staartvin** [comment]
Could you turn debug on and let Autorank run for a full day. Then report back the console log.

**Comment by PneumaticHeal** [comment]
How do I turn on debug? With /ar debug? That only seemed to create a file

**Comment by Staartvin** [comment]
You can turn it on in the Settings config: https://github.com/Armarr/Autorank-2/blob/master/Settings.yml#L81

**Comment by Staartvin** [comment]
Closed due to inactivity.
