### ISSUE TITLE
AR not promoting..

### ISSUE THREAD

**Issue by cooperisdunn** [Armarr/Autorank-2#235]
Okay. So I'm using Build 3.5.1 (latest build on spigot). Autorank is loading correctly, with no errors and properly counting player time. Where my issue is stemming from, I cannot pinpoint. Sometimes the plugin works with promoting players, and other times it does not. For example: PlayerA joins, plays 5 minutes, and is autorank'd up to the next rank, as defined in simple config. However, PlayerB joins, plays for four hours (as checked by /ar check) but has not been ranked up at all. The message received upon /ar check'ing is that PlayerB cannot rank up because he is/ has already been that rank. Nothing else but Autorank touches ranks on my server. There is no way PlayerB couldve already been the next rank without Autorank promoting him to that rank. Any help would be greatly appreciated.

**Comment by cooperisdunn** [comment]
Could the problem be autorank thinking its promoted that player but actually hasn't? I'm using pex running latest spigot build.

**Comment by Staartvin** [comment]
You should set 'allow infinite ranking' to true in the Settings.yml:

https://github.com/Armarr/Autorank-2/blob/master/Settings.yml#L85

**Comment by cooperisdunn** [comment]
Staartvin,

That kind of solves the problem. However, it does not fix the underlying issue at all. With 'allow infinite ranking' set to true in the settings.yml, the plugin promotes and demotes wildly. After 5 minutes of in-game time the plugin will promote someone to the next rank, but will demote them after a relog or something and its quite confusing for the player.

**Comment by Staartvin** [comment]
Could you give your advanced config?

**Comment by cooperisdunn** [comment]
I use simple config, autoranks built in promoting system.

**Comment by Staartvin** [comment]
Could you contact me on Skype? I would like to further investigate on this issue. My username: Staartvin

**Comment by cooperisdunn** [comment]
Okay

**Comment by Staartvin** [comment]
Closed due to inactivity.
