### ISSUE TITLE
Autorank cannot find 3rd group and tells players they are in last rank up group.

### ISSUE THREAD

**Issue by OttoX4** [Armarr/Autorank-2#236]
Keep receiving error message in-game: Rank line of rank 'default' is invalid. Group 'regular' dosen't exist!
![2015-06-26_20 51 57](https://cloud.githubusercontent.com/assets/13072247/8389973/47b1c80a-1c45-11e5-8ff6-2baf8fcb419a.png)

And players cannot rankup From Regular to Member!

[Removed due to formatting]

**Comment by OttoX4** [comment]
The groups config is fine, it gives off no warnings or errors.  Autorank is the plugins causing issues...

**Comment by Staartvin** [comment]
Could you provide your config and permissions file (via pastebin)?

**Comment by OttoX4** [comment]
http://pastebin.com/CXpnfvJQ


and groups config:

http://pastebin.com/xeEB8Jmd

autorank settings:

http://pastebin.com/152uvMHV

**Comment by cooperisdunn** [comment]
Case.

**Comment by OttoX4** [comment]
???

**Comment by OttoX4** [comment]
OK found the issue after cooperisdunn's tip:  Note in my groups file I have the rank's name capitalized, but in the simple config, it is not capitalized.

**Comment by cooperisdunn** [comment]
I should have explained myself further, sorry I was in a little bit of a rush. I'm glad you found the solution :-)

**Comment by OttoX4** [comment]
Thanks for the help!
