### ISSUE TITLE
AutoRank Tracking Issue

### ISSUE THREAD

**Issue by piecrustyumyum** [Armarr/Autorank-2#237]
Autorank is not tracking mobs killed. Not sure why it does this.

**Comment by Staartvin** [comment]
Could you provide your config?

**Comment by piecrustyumyum** [comment]
sure um here
http://pastebin.com/2VM7Kp1Y
This is the advanced config. and no I am not using stats. I kinda figured I needed stats but stats like breaks autorank for some reason. I can try to get a pastebin of the error but whenever I add stats it never works.

**Comment by Staartvin** [comment]
You need Stats for Autorank to be able to track mob kills.
