### ISSUE TITLE
Tracking Multiple Perms Group

### ISSUE THREAD

**Issue by Zerthick** [Armarr/Autorank-2#239]
Hello, I run an McMmo server and have been depending on Autorank ever since I switched to 1.8.  I wanted to request if it would be possible for autorank to track multiple permissions groups for the same player.  The reason I request this is that we have special ranks on my server for donators and such, however I don't want these ranks to get in the way of players progressing through the normal ranking ladder. However, whenever my moderators add these players into these special groups alongside their normal player ranks, autorank forgets where the player is in the ranking ladder and refuses to continue ranking them. Doing /ar check <player> on the player in question reveals that they are only in the special donator group according to autorank.   I'm using the latest version of autorank along with permissionsEx 1.23.2.

Thanks!

**Comment by Staartvin** [comment]
Could you give me an example of what the rank ladder looks like? Could you also provide your PEX config?

**Comment by Zerthick** [comment]
Let's say I have 3 normal ranks, rank 1, rank 2, and rank 3.  I also have a special donator rank that adds a * suffix to players names.  Suppose a player is in rank 2 and decides to donate.  My moderators then add him to the special donator rank so he can get the *. So now the player is in rank 2 AND the donator rank.  However, when the player meets the specified requirements for rank 3 Autorank will no longer rank him up and doing /ar check on him shows only the donator rank, not rank 2.  This is oversimplified but my actual config has ~30 ranks so it would probably just make this more confusing.

**Comment by TNTUP** [comment]
Sorry to reply here, try this build (Notice this is a dev build and at your own risk) at this link: http://62.131.38.74:8080/job/Autorank/355/Autorank$Autorank/

The dev replied to me, he will try reverting it if possible.

**Comment by Staartvin** [comment]
Build 399 (http://62.131.38.74:8080/job/Autorank/399/) has an option to switch between 'primary group' or 'all groups'. (https://github.com/Armarr/Autorank-2/blob/master/Settings.yml#L94)

**Comment by DeathStapler** [comment]
This might be similar to what Zerthick was trying to do, so hopefully my issue will contribute to solving theirs.

##### Issue
When I tried the setup below and someone would rankup, they would lose the primary and secondary group and now only have the one that they ranked up to.   So if a player was in the groups Member and L0, then ranked-up to L1, they would only be in the L1 group.  The player loses the Member group.

##### Using
KCauldron: 1.7.10-1492.152
PermissionsEX: 1.22.9
AutoRank: 3.6-Dev-436

##### Setup
I have primary groups, let's say: Guest, Member, VIP, Admin, Owner

I also have secondary groups that simply add a suffix to their name in chat, let's say: L0, L1, L2, L3, L4, etc...

Each player would start with the default groups of Guest and L0.  Over time a player might have:

Player|Groups
--------|-------
SnubDub| Guest, L1
LundGrund| Member, L2
FethBeth| VIP, L2
BossHoss|Admin,L0

##### Config File
    # This would be an example AdvancedConfig.yml
    ranks:
        L0:
            requirements:
                time:
                    value: 5d
            results:
                rank change: L0;L1
                message: 'Congratulations, you are now a Level 1.'
         L1:
            requirements:
                time:
                    value: 10d
            results:
                rank change: L1;L2
                message: 'Congratulations, you are now a Level 2.'
         Guest:
            requirements:
                time:
                    value: 3d
                exp:
                    value: 20
            results:
                rank change: Guest;Member
                message: 'Congratulations, you are now a Member.'
         Member:
            requirements:
                time:
                    value: 25d
                exp:
                    value: 100
            results:
                rank change: Member;VIP
                message: 'Congratulations, you are now a VIP.'

 I did change this value in Settings.yml:
`use primary group for vault: false`

**Comment by Staartvin** [comment]
@Zerthick Could you create a new issue of github? That is better manageable as your issue seems to be a little different.

**Comment by DeathStapler** [comment]
Issue move.  Feel free to delete my post.

**Comment by Staartvin** [comment]
Issue solved.
