### ISSUE TITLE
How would I run a command to automove a player to a new group?

### ISSUE THREAD

**Issue by PsychoNavigator** [Armarr/Autorank-2#240]
The catch here is that I use McMyAdmin to manage players and permissions, so I have to push the players names manually as MCMA overwrites the group and perms on every restart/change.

Essentially I need to push a command to the backend to move a player from intern(default) to employee(trusted). How do I pull this off?

**Comment by Staartvin** [comment]
From an employee of McMyAdmin:

"
To work with MCMA user and groups, they'd need to be able to use /pushcommand - which is how instructions can be pushed from MCMA by other plugins. This also requires that MCMAs compatibility plugin is running. 

It'd look something like this: 

/pushcommand addmember GROUP USER
"

You have to add a command result that will update the player to the proper rank. So if you're using PEX for example, you would do '/pushcommand pex user &p group set groupname'. That should update the McMyAdmin perms for that player.

**Comment by Staartvin** [comment]
Closed due to inactivity.
