### ISSUE TITLE
mcMMO loads players on a seperate thread and cannot give playerdata on login

### ISSUE THREAD

**Issue by t00thpick1** [Armarr/Autorank-2#248]
https://github.com/mcMMO-Dev/mcMMO/issues/2538

This was reported to me and I have determined it is not an issue with mcMMO.  Quite a while ago(a year or so?) we moved player data loading to its own thread as opposed to loading it immediately on login, this is to alleviate the heavy processing and not put a load on the server.  However, your plugin is querying mcMMO for data while the player is not yet loaded.  To fix this you can either wait a tad to do your logic, or you can switch your system to instead use:  
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/api/ExperienceAPI.java#L688

**Comment by Staartvin** [comment]
Ah, thank you.  I wasn't sure why this was happening with mcMMO.  You could maybe implement a way so it  doesn't error, but instead gives cached values if a 'true'  parameter was given with the method. I'll be using the experience api offline method.

**Comment by TheChampTF** [comment]
Let me know if you need me to test something (:

**Comment by Staartvin** [comment]
You should try build 413, @TheChampTF

**Comment by TheChampTF** [comment]
Tried that version and latest 416

Keep getting: 16:27:03 INFO]: [Autorank] Could not fetch UUID of player 'PlayerName'!

It just keeps running thru all the names.

**Comment by TheChampTF** [comment]
Still the same on 434

**Comment by TheChampTF** [comment]
Looks fixed on latest build (Stabil version, not dev.)

So thanks for that!

**Comment by Staartvin** [comment]
Great!
