### ISSUE TITLE
[SOLVED] Ar Check causes internal server error

### ISSUE THREAD

**Issue by SoulReturns** [Armarr/Autorank-2#251]
Config (It's big)
http://pastebin.com/bw5kzSqd

Console Error
16.08 22:15:11 [Server] INFO ... 15 more 16.08 22:15:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:141) ~[?:?] 16.08 22:15:11 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:326) ~[?:?] 16.08 22:15:11 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:49) ~[?:?] 16.08 22:15:11 [Server] INFO at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:90) ~[?:?] 16.08 22:15:11 [Server] INFO at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:88) ~[?:?] 16.08 22:15:11 [Server] INFO Caused by: java.lang.NullPointerException 16.08 22:15:11 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05] 16.08 22:15:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-d97e08b-880a532] 16.08 22:15:11 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.6 16.08 22:15:11 [Server] ERROR null 16.08 22:15:11 [Server] INFO SoulReturns issued server command: /ar check

I just finished all of my ranks and I have no idea what could be going on.

**Comment by SoulReturns** [comment]
I was missing a single quote. Solved.

**Comment by Henaminator** [comment]
I have the same problem
