### ISSUE TITLE
Unhandled exception executing command 'ar' in plugin Autorank v3.6

### ISSUE THREAD

**Issue by GiuseppeGroth** [Armarr/Autorank-2#253]
http://pastebin.com/k7pwut2X
http://pastebin.com/9pSyP1Y6
http://pastebin.com/Zbxdp8SQ
http://pastebin.com/bmxhP2ML
http://pastebin.com/aViFdKtp
http://pastebin.com/0quhqZqa

**Comment by Staartvin** [comment]
Closed due to inactivity.
