### ISSUE TITLE
An unexpected error.

### ISSUE THREAD

**Issue by Henaminator** [Armarr/Autorank-2#255]
Hi, i get this message when i try to use /ar check 
Image: http://snag.gy/yb1iR.jpg

I can see how long they played for but I cant see what they have completed, it worked before and suddenly this came up.

Debug file: http://pastebin.com/PsKcnTm1

**Comment by Staartvin** [comment]
Could you provide your AdvancedConfig.yml?

**Comment by Henaminator** [comment]
http://pastebin.com/JLqNyP2C

**Comment by Staartvin** [comment]
Whenever you get the error in game, could you look in the console and give me the output of what is shows?

**Comment by Henaminator** [comment]
02.09 19:53:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:141) ~[?:?]
02.09 19:53:02 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:311) ~[?:?]
02.09 19:53:02 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:265) ~[?:?]
02.09 19:53:02 [Server] INFO at me.armar.plugins.autorank.playerchecker.PlayerChecker.getRequirementsInStringList(PlayerChecker.java:189) ~[?:?]
02.09 19:53:02 [Server] INFO at me.armar.plugins.autorank.playerchecker.requirement.MoneyRequirement.getDescription(MoneyRequirement.java:19) ~[?:?]
02.09 19:53:02 [Server] INFO Caused by: java.lang.NullPointerException
02.09 19:53:02 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
02.09 19:53:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d97e08b-880a532]
02.09 19:53:02 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.6
02.09 19:53:02 [Server] ERROR null

**Comment by Staartvin** [comment]
Closed due to inactivity.
