### ISSUE TITLE
Votes not being counted in /ar check 

### ISSUE THREAD

**Issue by donnie8986** [Armarr/Autorank-2#256]
Hello, 

I've had Autorank on my server for as long as I can remember. It wasn't until earlier this year that i decided to create an advanced config file. I am currently having issues with votes being counted for players through Autorank. Any idea what could be the issue? Autorank does not present any issues in console for me. Thanks in advance! 

Donnie

**Comment by Henaminator** [comment]
I have the same problem, and im using galistener

**Comment by Staartvin** [comment]
You should use Votifier and Stats 3 (if you are using Autorank 3.6). Are you using that?

**Comment by Staartvin** [comment]
Closed due to inactivity.
