### ISSUE TITLE
Not Converting Flatfile to MySQL

### ISSUE THREAD

**Issue by CathalCraft** [Armarr/Autorank-2#257]
I've been using Flatfile storage for Autorank, but I want to transfer it to MySQL now. I entered in my correct MySQL information and it connected, but it isn't converting my Flatfile data to MySQL. Would you look into adding support for this, please?

**Comment by Staartvin** [comment]
Autoranks MySQL works a little differently from other plugins. The MySQL is only used when you have a server network that is running multiple Minecraft servers.

**Comment by Staartvin** [comment]
It is not meant to be a replacement for the flat file system

**Comment by CathalCraft** [comment]
I plan to add more servers to my network that use Autorank. Does using MySQL just push data from one server to the other one?

**Comment by Staartvin** [comment]
When MySQL is enabled for multiple servers, each local server with Autorank on it, will push to the database you specify. When setting up MySQL on each server, don't forget to /ar sync after you're done on each server once!

**Comment by Staartvin** [comment]
Closed due to inactivity.
