### ISSUE TITLE
Internal errer when trying /ar check

### ISSUE THREAD

**Issue by dierke9** [Armarr/Autorank-2#258]
When i try to do /ar check it just says: " An internal error accured while attempting to perform this command"

**Comment by Staartvin** [comment]
Could you provide the most recent server log?

**Comment by dierke9** [comment]
https://www.dropbox.com/s/a4ku0jey9regbwe/latest.log?dl=0

**Comment by Henaminator** [comment]
I had the same problem, if you have multiverse download multiverse from spigot.

**Comment by Staartvin** [comment]
Closed due to inactivity.
