### ISSUE TITLE
An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by Tarantula99nl** [Armarr/Autorank-2#260]
Hello,

i have Autorank installed and setup, but when i try /ar check, it gives the error: An internal error occurred while attempting to perform this command.

i have tried /ar debug and it gave me this file: http://pastebin.com/kyt5Li2s

can you please help me?

**Comment by Staartvin** [comment]
Can you provide the console log of when the error occured/occurs?

**Comment by Tarantula99nl** [comment]
http://pastebin.com/JyTv5eMd

Here it is

**Comment by Staartvin** [comment]
Closed due to inactivity.
