### ISSUE TITLE
ZERO vote support.

### ISSUE THREAD

**Issue by Zilacon** [Armarr/Autorank-2#263]
I setup Autorank on 16 of my servers from 1.7.10 to 1.5.2 all of them have stats and everything is properly enabled.

Everytime someone votes autorank does not even notice. What is the purpose of having a vote requirement when there is no votifier listener?

Cause the versions from 1.5.2 to 1.7.10 have the exact same problem.

**Comment by Staartvin** [comment]
Removed due to inactivity.
