### ISSUE TITLE
Using symbols in Rank/Group names

### ISSUE THREAD

**Issue by neo4uo** [Armarr/Autorank-2#268]
I keep getting an java error in the console with AutoRank. I believe it could be related to using a symbol in my ranks. One of my ranks in pex is citizen+  and it seems to be failing because of the + symbol. Are symbols not allowed?

Thanks

**Comment by Staartvin** [comment]
I'm not sure, I haven't tested symbols. Can you show me the error you're getting + the advancedconfig you are using?

**Comment by neo4uo** [comment]
I am actually using the simpleconfig to try to narrow down the bugs, here is the message I am getting
19:40:02 [WARN] org.apache.commons.lang.UnhandledException: Plugin Autorank v3.6 generated an exception while executing task 46
19:40:02 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
19:40:02 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
19:40:02 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
19:40:02 at java.lang.Thread.run(Unknown Source)
19:40:02 Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
19:40:02 at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372)
19:40:02 at me.armar.plugins.autorank.permissions.handlers.VaultPermissionsHandler.getGroups(VaultPermissionsHandler.java:74)
19:40:02 at me.armar.plugins.autorank.validations.PermissionGroupValidation.validateSimpleGroups(PermissionGroupValidation.java:244)
19:40:02 at me.armar.plugins.autorank.validations.ValidateHandler.validateConfigGroups(ValidateHandler.java:26)
19:40:02 at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:338)
19:40:02 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19:40:02 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

**Comment by Staartvin** [comment]
It seems you're using the wrong version of Vault and PermissionsEx. Which version do you have?

**Comment by neo4uo** [comment]
Hey you were right I was running two servers, I updated the files in Vault and PermissionsEx and it fire up. Also I had a typo with the plus sign, AutoRank does parse ranks with a + :)

**Comment by Staartvin** [comment]
Good to hear it all worked out! Happy Autorank-ing!
