### ISSUE TITLE
Auto Rank Error with Advance Config

### ISSUE THREAD

**Issue by neo4uo** [Armarr/Autorank-2#269]
AutoRank is throwing errors since I switched over to Advanced Config, if you could point me in the right dirrection :)

Error log when using /ar reload

http://pastebin.com/qsqvMswk

simple config:
http://pastebin.com/1HWzi0dW

advanced config:
http://pastebin.com/WrawVk7a

settings:
http://pastebin.com/DpiECXM9

Thanks :)

**Comment by Staartvin** [comment]
You used tabs (\t), these are not allowed in YAML. This is the fixed version of your config: http://pastebin.com/vcKvMuyT

**Comment by neo4uo** [comment]
Staartvin,
Thanks I feel like a newb :( WoW Yaml is very strict I didn't realize there was a tab, guess it was in the error log :( anyways I found an online Yaml Parser thanks alot again :)

**Comment by Staartvin** [comment]
No problem, always use a YAML parser ;)
