### ISSUE TITLE
Error with Stats

### ISSUE THREAD

**Issue by donnie8986** [Armarr/Autorank-2#270]
Hello, 

I keep receiving this error in console: http://pastebin.com/nxaY5mdt. I loaded the Stats plugin first and no errors occurred. However when I loaded in autorank, I got that error. Moreover, when I type /ar check in chat, it states "autorank is disabled. Check server log." Thanks for the help in advance!

Donnie

**Comment by Staartvin** [comment]
You have the wrong version of Stats on your server. Get the correct version of Stats for Autorank 3.5.1.

**Comment by Staartvin** [comment]
Removed due to inactivity.
