### ISSUE TITLE
Issues with UUID

### ISSUE THREAD

**Issue by carelli99** [Armarr/Autorank-2#271]
Hello, man i have issues with UUID of players:
12.11 23:18:11 [Server] INFO Could not find name of account with uuid: '1e61af4b-a191-323f-99f1-67f660e846df'
12.11 23:18:11 [Server] WARN at java.lang.Thread.run(Unknown Source)
12.11 23:18:11 [Server] WARN at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
12.11 23:18:11 [Server] WARN at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
12.11 23:18:11 [Server] WARN at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
12.11 23:18:11 [Server] WARN at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
12.11 23:18:11 [Server] WARN at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
12.11 23:18:11 [Server] WARN Unexpected token END OF FILE at position 0.
Spigot: 1.8.8
Autorank: V.6 dev
help?

**Comment by carelli99** [comment]
up

**Comment by Staartvin** [comment]
When does this happen?

**Comment by carelli99** [comment]
only when the i start server

**Comment by carelli99** [comment]
only when i start server

**Comment by carelli99** [comment]
Can you help me? I neefd this

**Comment by Staartvin** [comment]
Removed due to inactivity.
