### ISSUE TITLE
Rank change of rank X is invalid. the rank to promote from doesnt exist.

### ISSUE THREAD

**Issue by Mathiaskruse** [Armarr/Autorank-2#272]
![2015-12-10_12 03 19](https://cloud.githubusercontent.com/assets/4289557/11713902/76bca20e-9f36-11e5-94ec-e91574ee6572.png)

This is the error i get, continously ingame, no console errors.

I checked my Permissions file, i checked my AutoRank AdvancedConfig file, and i let a bunch of others check it. No errors...

Any ideas?

**Comment by Mathiaskruse** [comment]
Here's my config files

**Comment by Mathiaskruse** [comment]
Well, furthermore. I just tested this at one of my players. When i make them "Snow" Rank. and i try to promote it says:

Promotion error: User are not in this ladder,

but when he reaches the desired playtime he ranks up as following the ladder anyways... so weird :100:

**Comment by Staartvin** [comment]
Removed due to inactivity.
