### ISSUE TITLE
[Hooking] Get an error?

### ISSUE THREAD

**Issue by Sinder33** [Armarr/Autorank-2#273]
When I try to /ar hook I get an error, and I can't get the stats to work with Autorank? I downloaded the stats plugin from bukkit, you can see the error code below :) Both versions are downloaded from bukkit's website (The standard download button)

http://pastebin.com/s6JTkmwV

If the problem is wrong version, please link me to the correct version

**Comment by Staartvin** [comment]
Use the versions that are on Spigot, those are updated ;)
