### ISSUE TITLE
Time reset

### ISSUE THREAD

**Issue by DavideBlade** [Armarr/Autorank-2#274]
Sometimes, users always different reset the playing time and therefore, must start again in order to climb to the next rank. I can do about it?

Sorry for bad english but i'm italian.

**Comment by Staartvin** [comment]
Hmm, I don't really understand you :(

**Comment by DavideBlade** [comment]
Eg: I have played in a server for 10 days and are passed from rank A to rank C. When the server returned and after /ar check I am told that I only played for 20 seconds instead of telling me 10 days.
The time and the rank are random.

Now you have understood?

**Comment by Staartvin** [comment]
Removed due to inactivity.

**Comment by DavideBlade** [comment]
I was just waiting for your reply...
