### ISSUE TITLE
Compatiblity with PlayerPoints?

### ISSUE THREAD

**Issue by kasper227232** [Armarr/Autorank-2#275]
Hello.

This isnt really an issue i just have a question.

Do you think there would be a possibilty to make PlayerPoints compatible with AutoRank? Since i would love to use AutoRank for a RPG Leveling System.

**Comment by Staartvin** [comment]
I'm not really working on Autorank anymore as I do not have the time for it. I'm waiting for another developer(s) to take over. Sorry!
