### ISSUE TITLE
global time

### ISSUE THREAD

**Issue by Ironic8b498** [Armarr/Autorank-2#277]
Just switched to a Bungee network and using SQL, everything is working fine, just need to know how to add global time to all my players so I can make things fair, since it's been a few months since I started to use Autorank and want to use global time in the rank ups. Or is there a way to get printed list of player and time on one server?

**Comment by Staartvin** [comment]
You can use /ar sync to sync their time or use /ar gadd <player> <amount>!

**Comment by Staartvin** [comment]
Removed due to inactivity.
