### ISSUE TITLE
There are invalid groups defined in the config.

### ISSUE THREAD

**Issue by Nextshot** [Armarr/Autorank-2#278]
It is beating me up...
Everything is correct in my vision...
I really dont know what is wrong with this anymore...
http://pastebin.com/0DJQtuMe

**Comment by Staartvin** [comment]
It seems that your rank change of  Veterano is 'rank change: Veterano;Avançado', the cedille on the c, when your group is called 'Avancado' without a cedille!

**Comment by Nextshot** [comment]
You are right... 
I saw that and run here to close the thread.
Now its fine :3 Thanks
