### ISSUE TITLE
Where to Configure Backups

### ISSUE THREAD

**Issue by SioWolf** [Armarr/Autorank-2#279]
I can not figure out how to or where to set up how often Autorank will create backups, nor how long it will keep them. I want it to back up my data.yml file and UUID folder every 12 hours and keep the backups for 3 days.

**Comment by Staartvin** [comment]
Autorank will backup your data.yml and playerdata.yml in the 'backups' folder inside the 'Autorank' folder every 24 hours. This is currently not changeable.

**Comment by Staartvin** [comment]
Close due to inactivity.
