### ISSUE TITLE
Ar check and leaderboard support Monthly, Weekly and day time!

### ISSUE THREAD

**Issue by Nesseley** [Armarr/Autorank-2#283]
Hey, it's me again! :)

I would really like to see you implement monthly, Weekly and daily time.

/ar check (player)will look something like this:
User is in the group GROUP!
Total Time: TIME
Monthly: TIME
Weekly: TIME
Daily: TIME
Requirements for nest rankup: REQUIRE

Also a leaderboard for each of the times.
/ar leaderboard(top) shows totaltime.
/ar leaderboard(top) monthly
/ar leaderboard(top) weekly
/ar leaderboard(top) daily

Would also be great for many players if leaderboard had a /ar top command! since most plugins use top these days.
(This will need a converter for data.yml, just a reminder.)

Hopefully this will be implemented in the furure.
Keep going strong.
- Nesseley

**Comment by Staartvin** [comment]
/ar top has been added and is in the next dev build!

**Comment by Staartvin** [comment]
Support built in Autorank 3.7!
