### ISSUE TITLE
Autorank not hooking into Stats

### ISSUE THREAD

**Issue by NaifB** [Armarr/Autorank-2#284]
I'm using Autorank 3.7 and Stats 2.0.1, they're both working properly individually but not working together (in MySQL I can see everything from Stats working)

19.01 17:54:02 [Server] INFO Autorank 3.7 has been enabled!
19.01 17:54:02 [Server] INFO Using timings of: autorank
19.01 17:54:02 [Server] INFO Language file loaded (lang.yml)
19.01 17:54:02 [Server] INFO Data file loaded
19.01 17:54:02 [Server] INFO Interval check every 5 minutes.
19.01 17:54:02 [Server] INFO Loaded libraries and dependencies
19.01 17:54:02 [Server] INFO Couldn't hook into Stats! Make sure the version is correct and Stats properly connects to your MySQL database.
19.01 17:54:02 [Server] INFO Stats (by Lolmewn) is not enabled!
19.01 17:54:02 [Server] INFO Found Stats plugin: Stats (by Lolmewn)
19.01 17:54:02 [Server] INFO Could not find Stats because it's probably disabled! Does Stats properly connect to your MySQL database?
19.01 17:54:02 [Server] INFO Successfully established connection to ---(ip hidden)---
19.01 17:54:02 [Server] INFO Loaded playerdata.
19.01 17:54:02 [Server] INFO Loaded stored uuids.
19.01 17:54:02 [Server] INFO Backup data file loaded (backup-data.yml)
19.01 17:54:02 [Server] INFO Internal properties file loaded
19.01 17:54:02 [Server] INFO Settings config file loaded
19.01 17:54:02 [Server] INFO Advanced config file loaded
19.01 17:54:02 [Server] INFO Simple config file loaded
19.01 17:54:02 [Server] INFO Enabling Autorank v3.7

**Comment by NaifB** [comment]
Awaiting your response, need it ASAP!

**Comment by Staartvin** [comment]
You'll need Stats 3, right now you're using Stats 2.
Autorank 3.6+ requires Stats 3.

**Comment by Staartvin** [comment]
Removed due to inactivity.
