### ISSUE TITLE
AutoRank not properly connecting with GroupManager/Essentials?

### ISSUE THREAD

**Issue by MrTom7** [Armarr/Autorank-2#285]
Hello,

I am currently running on AutoRank 3.7.1 (issue also occurred in previous version) and I am having an issue where I will rank someone up through GroupManager and it will not translate over to Autorank. So for example, a donator rank on our server is Ultimate. I have an Ultimate who is still an Elite (Regular rank, highest rank in the AutoRank chain) who is displaying that rank instead of the proper one. I'm not certain if this is a GroupManager Issue or a AutoRank issue, but I would just like to be certain on both ends.

![issue](https://cloud.githubusercontent.com/assets/16870514/12540213/399e6dce-c2d3-11e5-8679-464cf48a1d92.png)

Here is the pastebin of the most recent Debug file.
http://pastebin.com/G7AA0i81

Best Regards, 
Tom

**Comment by Staartvin** [comment]
Can you show ms your advanced configuration? Also, why does it show (Elite) as a prefix when the guy is an Ultimate?

**Comment by MrTom7** [comment]
Hi,

That is what I am trying to find out. AutoRank seems to not be picking this information up from GroupManager, and stays at the last rank in the chain, rather than update to the rank they actually have. 

We do not really use the Advanced Configuration but I have attached a pastebin of it down below.

http://pastebin.com/pMNqqChe

Regards.
Tom

**Comment by Staartvin** [comment]
Well, if you're using the SimpleConfig, could you show that one? It might be that if the prefix is not showing up, this could be an internal problem of GroupManager. The prefixes are handled by GroupManager, right?

**Comment by MrTom7** [comment]
Hi,

Here is the Simple Configuration:
http://pastebin.com/pS0cCwh9

Prefixes are handle by GroupManager yes. However, in the AutoRank system, they are still coming up as being the ranks within the simple configuration and not the rank they have in GroupManager. Im not sure, but it certainly could be an internal error with GM.

Regards,
Tom

**Comment by Staartvin** [comment]
Could you add me on Skype? (Staartvin) This is gonna take some investigating, so personal contact would be nice ;)

**Comment by Staartvin** [comment]
Closed due to inactivity.
