### ISSUE TITLE
,y server 

### ISSUE THREAD

**Issue by Nightltcreeper12** [Armarr/Autorank-2#288]
HOLY SHIT U GUYS ARE *****ES DOESNT WORK U RETARDS

**Comment by Nightltcreeper12** [comment]
U R SOO FUCKING STUPID

**Comment by philip-ulrich** [comment]
:-1:

**Comment by Nightltcreeper12** [comment]
Sorry ppl for swaering

**Comment by Staartvin** [comment]
I will always help, but I cannot help when you provide no error information.

**Comment by Nightltcreeper12** [comment]
Sorry the problem is that when i type th command it never works

**Comment by Staartvin** [comment]
Could you provide your server log?

**Comment by Nightltcreeper12** [comment]
No it changes

**Comment by Staartvin** [comment]
Closed due to inactivity.
