### ISSUE TITLE
Feature Request: A Skyblock integration

### ISSUE THREAD

**Issue by philip-ulrich** [Armarr/Autorank-2#289]
Hello! 

I just wanted to throw a feature request in here. I would like the ability to autorank based on variables in A Skyblock (https://www.spigotmc.org/resources/a-skyblock.1220/) parameters such as /is level and completion of challenges. Would this be something you could consider adding in the near future? :+1: :)

Thanks!
- Phil

**Comment by Staartvin** [comment]
Right now, Autorank supports ASkyBlock's island level: https://github.com/Armarr/Autorank-2/blob/master/AdvancedConfig.yml#L75

**Comment by philip-ulrich** [comment]
Oh. I'm so sorry. I didn't even notice that. Cheers! :+1:
