### ISSUE TITLE
WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.2 generated an exception while executing task 31

### ISSUE THREAD

**Issue by MomaCods** [Armarr/Autorank-2#290]
Can anyone help me with this warn?

I have 1.9 running on my server and just installed autorank 

My server is a fresh restart... for 1.9 so this auto rank warn is brand new ... any ideas?
![screen shot 03-06-16 at 08 55 am](https://cloud.githubusercontent.com/assets/17677132/13554577/77331b3c-e379-11e5-8589-55c4dd7d7b8b.PNG)

**Comment by Staartvin** [comment]
Could you provide your whole server log?

**Comment by MomaCods** [comment]
Yes I will

**Comment by Staartvin** [comment]
Closed due to inactivity.
