### ISSUE TITLE
Mcmmo

### ISSUE THREAD

**Issue by MomaCods** [Armarr/Autorank-2#291]
My mcmmo is not repairing ... it takes the items out of your inv and states on the screen "that felt easy" and I can see my levels raising ... but then  the item never repairs... and I never actually get any levels?

it is very odd indeed

this is the error console throws when someone is trying to repair..

Also this is the most recent Mcmmo I paid for it just 2 days ago

![screen shot 03-06-16 at 09 03 am](https://cloud.githubusercontent.com/assets/17677132/13554607/555ba528-e37a-11e5-8412-a4b41d195300.PNG)

**Comment by Staartvin** [comment]
I think this is an issue with mcmmo, not with Autorank. You should post this on the bug tracker of McMMO.

**Comment by TheChampTF** [comment]
Try this version https://ci.drtshock.net/job/MCMMO/94/
