### ISSUE TITLE
Not Working...

### ISSUE THREAD

**Issue by DutchUser** [Armarr/Autorank-2#292]
#############################################################################
#                                                                           #
#                   Autorank 2 Advanced Config                              #
#                                                                           #
#   Please use the SimpleConfig unless you know what you are doing and      #
#   need functionality that the SimpleConfig doesn't provide.               #
#                                                                           #
#############################################################################

ranks:
    Speler:
        requirements:
            time:
                value: 10h
        results:
            rank change: Starter;Speler
            command: 'say &p &2heeft rank &1*&aSpeler&1* &2gekregen omdat hij/zij langer dan &b10 uur &2heeft gespeeld op de server!'
            message: 'Gefeliciteerd! say &p Je bent gepromoveerd tot *Speler*!'
    Speler+:
        requirements:
            time:
                value: 50h
        results:
            rank change: Starter;Speler
            command: 'say &p &2heeft rank &1*&aSpeler+&1* &2gekregen omdat hij/zij langer dan &b50 uur &2heeft gespeeld op de server!'
            message: 'Gefeliciteerd! say &p Je bent gepromoveerd tot *Speler+*!'
           

Whats wrong? He says " Check your config!"

**Comment by DutchUser** [comment]
rfl. Do i know an site where i can post the file? He not doing that good here.

**Comment by DutchUser** [comment]
http://pastebin.com/t7nVWnts
http://pastebin.com/t7nVWnts

**Comment by Staartvin** [comment]
Could you post your server log?

**Comment by DutchUser** [comment]
http://pastebin.com/b1cGftaS

**Comment by Staartvin** [comment]
Rank change is not correct, for Speler it should be 'Speler;Speler+'. The first rank is the rank to rank from, the second is the rank to rank to. So 'Speler;Speler+' would rank a player for Speler to Speler+.

**Comment by DutchUser** [comment]
Still giving an error (The same as previous)

**Comment by DutchUser** [comment]
bump

**Comment by Staartvin** [comment]
Could you provide your new advanced config?

**Comment by DutchUser** [comment]
I will come on that tomorrow. For now i have an question. Is it possible to change colors in the message? (Both)

**Comment by DutchUser** [comment]
bump

**Comment by Staartvin** [comment]
You can change the messages and their colors in the lang file!

**Comment by DutchUser** [comment]
Where stands the promoot message then in lang
I have it about the
command: 'broadcast &p &2Heeft de rank &fSpeler &2Gekregen!'
message: 'Gefiliciteerd! Je bent nu [Speler]'

How can i change the colors in THAT message's

**Comment by DutchUser** [comment]
nvm
