### ISSUE TITLE
need autorank ignore group vip and vip+ when assigned with permissionex

### ISSUE THREAD

**Issue by fatdog66** [Armarr/Autorank-2#299]
Hi,

Can i tell autorank to ignore group VIP and VIP+ of permisisonex when a player buy this ? In case, the player of rank 1 play to go rank 2 and by charity he buy the VIP rank, he's unable to rank up anymore.

It's important for me to tell autorank to ignore the groups VIP and VIP+. Please help.

Thx.

Sorry for my english, i'm french.

**Comment by Nesseley** [comment]
It does this by default. Atleast my staff isnt ranking up by ontime.
Jusdt don't define the groups in the config if you don't want them to rank up.

**Comment by devonkeith** [comment]
f
