### ISSUE TITLE
Not entirely sure of the issue here.

### ISSUE THREAD

**Issue by RukuYukimura** [Armarr/Autorank-2#300]
In the console, i get "invalid groups defined in config" but they're not invalid, i double checked them.
the issue i think it might be is that the money requirements are too high? is there any way to extend this limit if there is one?

AdvancedConfig:
http://pastebin.com/623t8ACH

DebugInfo:
http://pastebin.com/Q7705vAk

**Comment by RukuYukimura** [comment]
Also the requirement to rank up from veteran to legend is 50 million but i got this...

1.Have at least 1.0E7

**Comment by RukuYukimura** [comment]
Issue solved, New Issue I'm trying to have Legend have two pathways - Legend to Reaper and Legend to Savior, each has different requirements, savior works but reaper doesn't...the players killed variable doesn't seem to work

**Comment by Staartvin** [comment]
Could you provide your new advanced config?

**Comment by Staartvin** [comment]
Closed due to inactivity.
