### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by DutchUser** [Armarr/Autorank-2#307]
09.04 00:40:07 [Server] WARN Exception in thread "Craft Scheduler Thread - 56" 
09.04 00:40:07 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.2 generated an exception while executing task 92
09.04 00:40:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
09.04 00:40:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
09.04 00:40:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
09.04 00:40:07 [Server] INFO at java.lang.Thread.run(Unknown Source)
09.04 00:40:07 [Server] INFO Caused by: java.lang.NullPointerException
09.04 00:40:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:39)
09.04 00:40:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:84)
09.04 00:40:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
09.04 00:40:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
09.04 00:40:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
09.04 00:40:07 [Server] INFO ... 3 more

**Comment by DutchUser** [comment]
PS: I am not sure if the plugin is not working ingame. I not tested yet. I can test that tomorrow.

**Comment by DutchUser** [comment]
an other error that also is in console: 
09.04 00:40:07 [Server] WARN Exception in thread "Craft Scheduler Thread - 56" 
09.04 00:40:07 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.2 generated an exception while executing task 92
09.04 00:40:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
09.04 00:40:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
09.04 00:40:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
09.04 00:40:07 [Server] INFO at java.lang.Thread.run(Unknown Source)
09.04 00:40:07 [Server] INFO Caused by: java.lang.NullPointerException
09.04 00:40:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:39)
09.04 00:40:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:84)
09.04 00:40:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
09.04 00:40:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
09.04 00:40:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
09.04 00:40:07 [Server] INFO ... 3 more
09.04 00:45:07 [Server] WARN Exception in thread "Craft Scheduler Thread - 63" 
09.04 00:45:07 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.2 generated an exception while executing task 92
09.04 00:45:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
09.04 00:45:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
09.04 00:45:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
09.04 00:45:07 [Server] INFO at java.lang.Thread.run(Unknown Source)
09.04 00:45:07 [Server] INFO Caused by: java.lang.NullPointerException
09.04 00:45:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:39)
09.04 00:45:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:84)
09.04 00:45:07 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
09.04 00:45:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
09.04 00:45:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
09.04 00:45:07 [Server] INFO ... 3 more

**Comment by DutchUser** [comment]
Again an error:
[09:19:04] [Server thread/ERROR]: [Autorank] Autorank lost its player checker, this is bad! Please report this to the developers!
[09:19:04] [Server thread/INFO]: Dovenschmitz[/81.70.140.9:49328] logged in with entity id 2530 at ([world]427.2304469065112, 95.0, -474.8937517904247)
[09:19:04] [Server thread/INFO]: Dovenschmitz is nu Online
[09:20:07] [Craft Scheduler Thread - 826/WARN]: Exception in thread "Craft Scheduler Thread - 826" 
[09:20:07] [Craft Scheduler Thread - 826/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.2 generated an exception while executing task 92
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:39)
	at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:84)
	at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Staartvin** [comment]
What version of Autorank are you using?

**Comment by DutchUser** [comment]
PluginVersion: Autorank v3.7.2
ServerVersion: Spigot 1.8.8 snapshot

**Comment by Staartvin** [comment]
Could you update to Autorank 3.7.3 and let me know if the problem still persists?

**Comment by DutchUser** [comment]
I just checked console and found this.
09.05 14:49:10 [Server] INFO Making a backup of data.yml.
09.05 14:49:10 [Server] INFO Checking for Updates ... 
09.05 14:49:10 [Server] INFO Making a backup of playerdata.yml.
09.05 14:49:10 [Server] WARN No files found, or Feed URL is bad.

Also i found this error. But i am not sure if it is from AutoRank

09.05 20:45:45 [Server] WARN The updater could not find any files for the project id 54358
09.05 20:45:45 [Server] WARN Couldn't check for updates.

[WARNING] Sometimes he have not error when he look for an update.
09.05 20:49:14 [Server] INFO Checking for Updates ... 
09.05 20:49:14 [Server] INFO No new version available

[PS] I am not sure IF this message's are from "AR"
