### ISSUE TITLE
Chat is spammed with an error

### ISSUE THREAD

**Issue by WoAnerges** [Armarr/Autorank-2#31]
"<AUTORANK> Warning: Permissions group is not defined: 'guest'"

What does this even mean? Every five seconds. I do not have any "guest" groups anywhere on my server. Please, stop this spam!

**Comment by RcExtract** [comment]
At default, the plugin uses SimpleConfig.yml which has a word 'guest' inside, generated defaultly.

**Comment by Staartvin** [comment]
You should update to the latest version of Autorank, as the SimpleConfig is no longer supported.
