### ISSUE TITLE
Help me to fix bug !

### ISSUE THREAD

**Issue by Melowelei** [Armarr/Autorank-2#313]
Here is config fonctional : http://pastebin.com/QCUWusez

Here my 2° config doesn't world : http://pastebin.com/f0HtrZJp

Here my error log for my 2° config : http://pastebin.com/8hp5JFn2 

Can u help me please ?

**Comment by Staartvin** [comment]
You should upgrade to Autorank 3.7, these spam errors were fixed in Autorank 3.7.

**Comment by Melowelei** [comment]
I tested the 3.7 but all my config was not good and the player worked /ar check and he auto upgraded

**Comment by Melowelei** [comment]
The problem is similar with Autorank 3.7 : 

Here is config fonctional : http://pastebin.com/QCUWusez

Here my 2° config doesn't world : http://pastebin.com/f0HtrZJp

New error log : http://pastebin.com/8rA7BZ8e

Soo, where is the problème now ?

**Comment by Staartvin** [comment]
The error says that you have a group 'Fermier' which has an requirement called 'has items'. This requirement does not exist: it must be 'has item' (without the s).

**Comment by Melowelei** [comment]
So all my problem is because i put has items and not has item xD ?

**Comment by Staartvin** [comment]
Yes, probably!

**Comment by Melowelei** [comment]
Soo, Thanks man !

**Comment by Staartvin** [comment]
No problemo! Glad I could help!

**Comment by Melowelei** [comment]
Hey

**Comment by Melowelei** [comment]
He hes saying me : <AUTORANK> Warning : Could not setup requiement 'has item'
My has item is like that : 
            has item2:
                value: reeds;338;64
I need to put whiout value ?

**Comment by Staartvin** [comment]
Take a look at the 'has item' requirement: https://github.com/Armarr/Autorank-2/wiki/Requirements-&-Results

**Comment by Melowelei** [comment]
id;amount;data;name;false/true

soo, for 64 stone is :
1:64:1:stone;false

**Comment by Melowelei** [comment]
Right ?

**Comment by Melowelei** [comment]
or stone:64:1:stone;false

**Comment by Staartvin** [comment]
It's 1;64 (stone has no data value, so it can be left out). Also, you don't have to specify a name or 'false' if it is false. Just 1;64 would suffice.

**Comment by Melowelei** [comment]
Hmm, oké :)

**Comment by Melowelei** [comment]
I test it now

**Comment by Melowelei** [comment]
Fermier:
        requirements:
            has item:
                value: 391;64
            has item2:
                value: 338;64
            has item3:
                value: 392;64
            has item4:
                value: 296;64
            has item5:
                value: 86;64
            has item6:
                value: 103;64
Like dat he is saying me : Warning : Could not setup requiement 'has item'
Why x) ?

**Comment by Staartvin** [comment]
Could you provide your whole config?

**Comment by Melowelei** [comment]
I don't want to give it in public, can i give u in private ?

**Comment by Staartvin** [comment]
Sure, PM me.

**Comment by Melowelei** [comment]
How can i ?
In your mail ?

**Comment by Melowelei** [comment]
I sended u in your mail mijnleraar@msn.com

**Comment by Staartvin** [comment]
Could you also provide the exact error log?

**Comment by Melowelei** [comment]
here is the log 
http://pastebin.com/8uT4XgPb

**Comment by Staartvin** [comment]
Could you try this build? http://62.131.38.74:8080/job/Autorank/514/

**Comment by Melowelei** [comment]
All work good excepte my group " Ecuyer " : 
http://pastebin.com/pwnt5Kuq

**Comment by Melowelei** [comment]
All is good, Thx bro for this issue !

**Comment by Staartvin** [comment]
Good to hear you fixed it!
