### ISSUE TITLE
Player get derank and reload ar check

### ISSUE THREAD

**Issue by Melowelei** [Armarr/Autorank-2#315]
My player all time when i restart my server he get her /ar check reloaded, and sometime he get deranked.
My logs autorank :
http://pastebin.com/7vxBPhJg
Thx for help me ...

**Comment by philip-ulrich** [comment]
Someone else is using derank! Yay.

Staartvin and I were working on this yesterday. 

Use the latest build from here: http://62.131.38.74:8080/job/Autorank/519/

Make sure you have partial complete, allow deranking, and infinite ranking set to true. 

Still having issue after that? Turn the debug on and run for a couple hours Send your advanced config, settings file, the entire server log from that time, and general information about your server (version, spigot? bukkit? paper?, permission plugin, etc.)

**Comment by Melowelei** [comment]
If you want to know if this bug is patched on your last build, yes it is !
3 Day and 0 derank / 0 ar check reloaded !

**Comment by philip-ulrich** [comment]
Cool. Glad to hear it! @Staartvin, I think this can be closed out.

**Comment by Staartvin** [comment]
Closed!
