### ISSUE TITLE
invalid group defined when valid

### ISSUE THREAD

**Issue by 2fast4u2** [Armarr/Autorank-2#317]
It says "There are invalid groups defined in the config!", when the groups are vaild.

![2016-04-28_21 24 19](https://cloud.githubusercontent.com/assets/18731441/14908134/bc33bfce-0d87-11e6-9519-7980c6f226af.png)

SimpleConfig:
Default: rank1 after 2h
rank1: rank2 after 4h
rank2: rank3 after 8h
rank3: rank4 after 16h
rank4: rank5 after 64h
rank6: rank7 after 128h

**Comment by Staartvin** [comment]
Can you show me your config?

**Comment by Staartvin** [comment]
And your perms file?

**Comment by 2fast4u2** [comment]
I am not using my advanced config. Also, I deleted the comments to see if they were the issue.

Simple Config:
Default: rank1 after 2h
rank1: rank2 after 4h
rank2: rank3 after 8h
rank3: rank4 after 16h
rank4: rank5 after 64h
rank6: rank7 after 128h

Permissions file:
groups:
  Default:
    build: true
    permissions:
    - essentials.signs.use.buy
    - essentials.me
    - essentials.signs.use
    - essentials.kit
    - essentials.spawn
    - essentials.warp.list
    - essentials.warp
    - essentials.warps.*
    - essentials.build
    - randomport.portself
    - modifyworld.*
    - essentials.kits.starter
    - essentials.balance
    - essentials.balance
    - essentials.pay
    - essentials.msg
    - essentials.r
    - essentials.delhome
    - essentials.home
    - essentials.sethome
    - essentials.tpa
    - essentials.tpahere
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.signs.use.*
    - chatfeelings.hug
    - chatfeelings.slap
    - chatfeelings.poke
    - chatfeelings.highfive
    - chatfeelings.yell
    - chatfeelings.bite
    - chatfeelings.shake
    - chatfeelings.snuggle
    - chatfeelings.facepalm
    - chatfeelings.stab
    - chatfeelings.kiss
    - chatfeelings.punch
    - chatfeelings.murder
    - auctions.command.bid
    - auctions.command.cancel
    - auctions.command.end
    - auctions.command.ignore
    - auctions.command.start
    options:
      prefix: '&a[Newly Spawned]&f'
      default: true
      rank: '8'
  Donator:
    build: true
    inheritance:
    - Default
    permissions:
    - essentials.kits.premium
    - essentials.hat
    options:
      prefix: '&6[Donator]&f'
  Admin:
    build: true
    inheritance:
    - Donator
    permissions:
    - essentials.gamemode
    - essentials.bans
    - essentials.unban
    - essentials.ipban
    - essentials.unipban
    - essentials.pardon
    - essentials.enchant
    options:
      prefix: '&4[&cAdmin&4]&f'
  Owner:
    build: true
    inheritance:
    - Admin
    permissions:
    - '*'
    options:
      prefix: '&4[Owner]'
  rank1:
    inheritance:
    - Default
    options:
      prefix: '&2[n00b]&f'
      rank: '7'
  rank2:
    inheritance:
    - rank1
    options:
      suffix: '&f'
      prefix: '&9[Beginner]&f'
      rank: '6'
  rank3:
    inheritance:
    - rank2
    options:
      prefix: '&1[Average]&f'
      rank: '5'
  rank4:
    inheritance:
    - rank3
    options:
      prefix: '&c[NotBad]&f'
      rank: '4'
  rank5:
    inheritance:
    - rank4
    options:
      prefix: '&4[PrettyGood]&f'
      rank: '3'
  rank6:
    inheritance:
    - rank5
    options:
      prefix: '&d[Respected]&f'
      rank: '2'
  rank7:
    inheritance:
    - rank6
    options:
      prefix: '&5[Godly]&f'
      rank: '1'
schema-version: 1
users:
  152d6a1d-b788-3edc-b680-a9ac7f9de619:
    options:
      name: 2fast4u
    group:
    - Owner
  f60ba892-22f5-3a21-aa1d-d89c30f33d62:
    group:
    - rank1
    options:
      name: alexplan
  97b7d91e-55e3-3424-9355-a898b4c0ca85:
    options:
      name: UnitedDonkeys
    group:
    - rank1
  afa0ba19-715a-3a29-9377-1c9fafa63bc1:
    group:
    - Default
    options:
      name: dickymousefunclu
  0ede1e2c-4663-304f-b090-480f362120c7:
    group:
    - Default
    options:
      name: 44eesstt

**Comment by Staartvin** [comment]
Hmm, that's really odd. It seems like it doesn't catch all permission groups. Can you add me (Staartvin) on Skype so we can sort this out?

**Comment by 2fast4u2** [comment]
Sure

**Comment by 2fast4u2** [comment]
I have requested to add you.

**Comment by 2fast4u2** [comment]
new thread: https://github.com/Armarr/Autorank-2/issues/326
