### ISSUE TITLE
Multiple instances of a requirement not recognised

### ISSUE THREAD

**Issue by Hayden2006** [Armarr/Autorank-2#320]
I have bukkit 1.9.2 and the latest stat3 and Autorank 3.7.3.

I want to have more than one requirement for killing mobs in each rank, for instance, 200 skeletons, 200 chickens, and 200 cows will be required, however only one (the last to be listed) shows up in game. The PasteBin is my config file, I have requirements commented out temporarily for my server.

http://pastebin.com/6s02mAX2

**Comment by Staartvin** [comment]
If you have multiple requirements of the same type in one rank, just add a number behind the name. So mobs killed1, mobs killed2, mobs killed3, mobs killed4, etc!

**Comment by Hayden2006** [comment]
I feel so dumb, i saw that in someone else's config as you sent this.

**Comment by Staartvin** [comment]
No problemo, glad I could help!
