### ISSUE TITLE
Dual Groups, can't promote via playtime (no rankup found)

### ISSUE THREAD

**Issue by CobaltSparkz** [Armarr/Autorank-2#323]
Hey! 

I'm not sure of the best method of doing this.

Essentially, I have two "tiers" of ranks, 1 gained via playtime ingame, which AutoRank does its thing with, the other are 4 ranks which are granted ingame via donation. These ranks have a few custom permission nodes, and a custom suffix.

The issue is, these groups are "added" via pex (/pex user <user> group add <DonatorRank>).

This means, I assume, AutoRank sees this person in both ranks, in this case, the DonatorRank, and because that's not in the SimpleConfig, it can't promote them.

Example: Person joins at Rank A, then via playtime goes to Rank B, then Rank C, Rank D.

Donation Ranks are Rank1, Rank2, Rank3.

Pex adds Rank2 to a player in RankB, meaning they are now both Rank 2 AND Rank B.

AutoRank can't "Exclude" groups when it looks at a player, so it cannot promote them and further.

Apologies for the long winded explanation, but I hope you get the idea :)

Many thanks

Sparky

**Comment by Staartvin** [comment]
So I think this is easily solvable: just set 'get primary group of vault' to false in the settings.yml! That should so it!

**Comment by CobaltSparkz** [comment]
Yep, that was all! I hadn't quite understood the config explanation, but it works - Thanks every so much for your help ^_^
