### ISSUE TITLE
invalid group defined when valid (Repost)

### ISSUE THREAD

**Issue by 2fast4u2** [Armarr/Autorank-2#326]
It says there are invalid groups defined in the config when they are valid.

Config: http://pastebin.com/6nfWVgfg
Permissions file: http://pastebin.com/by8RnzG1

Old thread: https://github.com/Armarr/Autorank-2/issues/317

**Comment by Nesseley** [comment]
I think you have to have 2 "normal" user groups.
Start with Guest then upgrade to Member after x amount of hours

Remember to make these in pex too, that can have all the same permissions

**Comment by 2fast4u2** [comment]
nope, didn't fix it.

**Comment by Nesseley** [comment]
Oh I dont read that too well. 
you have to define rankchange better.

http://pastebin.com/RbmedY4j
This is how to do it

**Comment by 2fast4u2** [comment]
It didn't work. I am still getting the error Rank1 not defined in the config. Also, I believe the syntax is rank change: <new rank>

**Comment by 2fast4u2** [comment]
Bumped to new thread
