### ISSUE TITLE
AutoRank - Votes reset

### ISSUE THREAD

**Issue by Metisuneatn** [Armarr/Autorank-2#341]
Hey there! Randomly for people their entire vote count resets. It doesn't happen to everyone, I would assume around 1 in 60 people get it reset randomly. Is there a way to just hook it into GAListener so it just reads off the number of votes gal uses? Or is there any way I can fix it for them? It all hooks into SQL so it is kinda weird to have this

**Comment by Staartvin** [comment]
I'm not sure why this is happening and I think this is a problem on the side of Votifier, not Autorank. Maybe contact their developer?

**Comment by Metisuneatn** [comment]
Well it might actually be the SQL. So we changed from using a third party SQL to local host and I haven't had any more reports. I do get the same complaint "I voted offline and it didn't count" but the random votes missing look likes it stopped

**Comment by Metisuneatn** [comment]
Nevermind my last post. It just happened. I'm not really sure why it would be votifier. So people get votes daily. 13 total and randomly people get 0 total for rank up. This last guy had 67 votes. his auto rank says 0/50. He's been the rank for 3 days.

**Comment by Staartvin** [comment]
So, to make it clear, do the votes stay in the SQL database? Or are they reset? If they get reset, Autorank is not the culprit as Autorank doesn't touch the SQL connections. If, however, the votes are persistent but Autorank doesn't count them, it's a problem on the side of Autorank.

**Comment by Metisuneatn** [comment]
It's like in the SQL I can see it but when the player does /ar track 1 (votes) it like doesnt show the info. I had it happen to my alt and when I saw it reset at 400 votes I logged off for two days. It told me 0/400. Then when I came back it said the correct number.  I personally saw my votes come back, I have not had any reports of others coming back, doubt they really look

**Comment by Staartvin** [comment]
So it does not actually clear the data in the SQL database. What version of Stats are you using?

**Comment by Metisuneatn** [comment]
Latest version from the Jenkins
