### ISSUE TITLE
Requirements aren't marked as "Done"

### ISSUE THREAD

**Issue by MitesMC** [Armarr/Autorank-2#342]
Hello, I am running autorank on a 1.9.4 spigot server. 

The advancedconfig has been checked and rechecked countless times. I have also made sure that capitalization and formatting are the same with that of PermissionsEx. Whenever a player does **/ar check** their playtime is recorded correctly as well as their mcmmo and balance details. 

However, despite several attempts completed requirements aren't marked as "Done" when a player does **/ar check**. So eventually, when the player completes all requirements to rank up, they do not get ranked up at all. 

Here's my AdvancedConfig.yml for further checking: [http://pastebin.com/YRkvL9Jn](http://pastebin.com/YRkvL9Jn)
Settings.yml: [http://pastebin.com/ALuWfdDL](http://pastebin.com/ALuWfdDL)

Any help is greatly appreciated as I've really tried everything I did to sort this out. Thank you!

**Comment by MitesMC** [comment]
@Staartvin or anyone who could help with this, please?

**Comment by Staartvin** [comment]
Your 'use partial completion' is turned to _false_. It should be set to _true_.

**Comment by MitesMC** [comment]
This has been resolved with the help of someone from the AutoRank discussion thread at Spigot. I forgot to drop by and update this issue ticket. Thank you anyway for the help. :)

**Comment by Staartvin** [comment]
Great to hear, sorry for the late reply.
