### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by DutchUser** [Armarr/Autorank-2#344]
Because you dont respond to my private mail i secide to just post it here.
-------------------------------------------------------------------------------------------------------------------
Because this not an bug(i think) i am not going make an ticket and ask it with an PM.

I just added an new rank that players can get with playing 30 hours. But he dont work. When i reload the plugin or load the plugin he says "ERROR Check your config!"

Version: Autorank v3.7.3 (Server: Spigot 1.9.4)
File: http://pastebin.com/9PT6FgUh
-------------------------------------------------------------------------------------------------------------------

**Comment by Staartvin** [comment]
Your Speler+ rank does not have a correct rank change. Currently, you have _rank change: Speler;Speler+_. However, it should be _rank change: Speler+;**Name of rank to rank up to**+_

**Comment by DutchUser** [comment]
Speler+ is an rank. I want player get from [Speler] going to [Speler+]

**Comment by Staartvin** [comment]
In that case, you should replace _Speler+_ on line 10 with _Speler_ and it should work.

**Comment by DutchUser** [comment]
Yep. Its fixed now :). I didnt know that thing.

**Comment by Staartvin** [comment]
Great :) :+1:
