### ISSUE TITLE
Ar Check not working!

### ISSUE THREAD

**Issue by iRealize** [Armarr/Autorank-2#346]
So I installed autorank becuase I thought it would be very helpfull for my server so i wouldnt have to custom code a plugin! I did some configing and then as a Member i did /ar check. And the error i got was: An internal error occurred while attempting to perform this command. Help! Here is config:

ranks:
    Member:
        requirements:
            time:
                value: 10h
        results:
            rank change: Member;Coal
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Coal!'
            message: 'Congratulations, you are now Coal!.'
    Coal:
        requirements:
            time:
                value: 1d
            players killed:
                value: 3
        results:
            rank change: Coal;Iron
            command: 'say &p has just been promoted to Iron!'
            message: 'Congratulations, you are now Iron!'

**Comment by Staartvin** [comment]
Could you use **pastebin.com** for your configs? Please provide your console.log and advancedconfig.yml
