### ISSUE TITLE
Thread pool leak.

### ISSUE THREAD

**Issue by henrikhierl** [Armarr/Autorank-2#349]
Autorank create more and more thread pools until server crash due to java limits. 

System setup: 
Ubuntu 16.10 
Spigot 1.10.2 latest build 
Plugins: 
Autorank 3.7.3 latest dev build (store mysql enabled)
Vault latest stable build

**Comment by TheChampTF** [comment]
Can confirm this also is happening on latest stable release.

**Comment by frizzbee30** [comment]
sounds like a similar issue I'm having in test with the latest release. it seems to be trying to do a mass backup of some sort and runs away

**Comment by Staartvin** [comment]
Hmm, can you send me the console.log or the exact errors you're getting?

**Comment by TheChampTF** [comment]
Well it looks like this [here](http://paste.yu8.me/?b4e8c6386837b9d5#M+BbF+/mOmRjtLFzw9jGzcrCT8G8pkzseIe9wiAToTg=) and just keep going. Of what I can see in the log it has at least 3 different strings going:

- uuids.get()
- playerName
- uuids

Hope it can help solve this.

**Comment by Staartvin** [comment]
Updating to 3.7.4 should solve this issue.

**Comment by TheChampTF** [comment]
That's the version I tried it on. 

Been a issue for me after Autorank v3.7.2

**Comment by henrikhierl** [comment]
We got following [error](http://paste.yu8.me/?b5815732e345db8c#itymXiXrSU6tVgOU8OFj0fu+Uw7o2o5axaBfq4MPXZ4=) several times (allows different plugin). Unfortunately there was no way to find out which plugin or class cause this, so we tested all plugin individually and find out that Autorank create more and more threads the longer it runs.
Currently we run without Autorank and we got no error anymore.

**Comment by Staartvin** [comment]
@henrikhierl What version are you running?

**Comment by henrikhierl** [comment]
@Staatvin Autorank 3.7.3 dev build #522

**Comment by Staartvin** [comment]
Could you try and update to 3.7.4 and see if anything changes?

**Comment by frizzbee30** [comment]
sorry, total facepalm..didn't look at the version at the top!! we updated to 3.7.4 (in test) and got the issue. I cant really post the log as it's over 2GB in size! 

I'm re running it and see if I can pull off a partial with ultraedit.

**Comment by frizzbee30** [comment]
ok, managed to kill it just after starting in test. It's too big for pastebin, and this was literally a kill just after boot. I've put it on dropbox. below.

https://www.dropbox.com/s/7rycb2vzjx9oxqx/latest.log?dl=0

**Comment by Staartvin** [comment]
I'm working on a fix, pushing a new release out today!

**Comment by Staartvin** [comment]
See https://www.spigotmc.org/resources/autorank.3239/update?update=101347 for Autorank 3.7.5!
