### ISSUE TITLE
Autorank is disabled. Check your server.log!

### ISSUE THREAD

**Issue by Aracasodius** [Armarr/Autorank-2#351]
Greetings,

Recently added your awesome plugin to my collection, noticed it refuses to work for some reason for me, truly don't know why. If you need any files, logs / configs just let me know!

Kind Regards, Aracas

**Comment by Staartvin** [comment]
Could you give me your server.log? Also, what version of Autorank are you running?

**Comment by Aracasodius** [comment]
Damn! The quick replies are real lol! Within a day, nice dude! 

http://pastebin.com/H8NJnbVw Here's the log, and the version we're rocking is 3.4!

**Comment by Staartvin** [comment]
It seems you are using the wrong version of Stats, make sure you are running the correct one. Also, not related to Autorank, McMMO seems to be having major issues on your server. You might want to contact the authors of mcmmo.

**Comment by Aracasodius** [comment]
What version should I be running? And do you think McMMO is causing the issues?

**Comment by Staartvin** [comment]
No, Mcmmo is not causing any issues concerning Autorank, but it is having issues on its own. 
I recommend upgrading to Autorank 3.7.6 as this is the latest version, but if you decide on running Autorank 3.4, you'll need Stats 2: http://dev.bukkit.org/bukkit-plugins/lolmewnstats/

**Comment by Aracasodius** [comment]
The reason I'm running Autorank 3.4 is because this is a 1.7.10 server. 
Plus, I was running this version before 
![image](https://cloud.githubusercontent.com/assets/6643430/16615858/bc4eb540-4379-11e6-9835-2d4707f69519.png) Which wasn't working.
Now I'm running this one
![image](https://cloud.githubusercontent.com/assets/6643430/16615869/cda31aac-4379-11e6-806a-44c41d38a90b.png)
Which also doesn't work.
I'll try updating to 3.7.6 though

**Comment by Staartvin** [comment]
Stats can be very buggy. If you use Autorank 3.7+ (that is, any version of 3.7 or later), you'll need Stats 3.

**Comment by Aracasodius** [comment]
It has been resolved, thank you good sir!
