### ISSUE TITLE
Configuration error....

### ISSUE THREAD

**Issue by wedza** [Armarr/Autorank-2#353]
Hello,

First, I want to yhan k you for your plugin, it's what I was searching for a long time, and it's super helpful for my server !

I configured today your plugin with the Advanced config, but I have a problem (I thing it's not a problem from your problem, but a bad cojnfiguration made by me), I couldn't find my error... Could you check this if you have the time ?

My config :
[AdvancedConfig.yml](http://pastebin.com/uKcmGcpJ)
[Settings.yml](http://pastebin.com/brNtd2FY)

The issue is that everytime that I star my server, this error happens : I cannot do any commands like /ar check or /ar track. I'm on Spigot 1.10-R0.1-SNAPSHOT.

`[11:21:14] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping in 'string', line 46, column 13: rank change: Jedi;MaitreJedi ^ expected , but found Scalar in 'string', line 48, column 47: ... ssage: 'Tu as passe 80 putain d'heures sur le serveur, tu est de ... ^ [11:21:14] [Server thread/WARN]: at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) [11:21:14] [Server thread/WARN]: at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) [11:21:14] [Server thread/WARN]: at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [11:21:14] [Server thread/WARN]: at me.armar.plugins.autorank.data.SimpleYamlConfiguration.(SimpleYamlConfiguration.java:69) [11:21:14] [Server thread/WARN]: at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:226) [11:21:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [11:21:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [11:21:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [11:21:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [11:21:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [11:21:14] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [11:21:14] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [11:21:14] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [11:21:14] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [11:21:14] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [11:21:14] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745) [11:21:14] [Server thread/WARN]: Caused by: while parsing a block mapping in 'string', line 46, column 13: rank change: Jedi;MaitreJedi ^ expected , but found Scalar in 'string', line 48, column 47: ... ssage: 'Tu as passe 80 putain d'heures sur le serveur, tu est de ... ^ [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [11:21:14] [Server thread/WARN]: at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [11:21:14] [Server thread/WARN]: at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [11:21:14] [Server thread/WARN]: ... 15 more`

and this one 

'[11:21:20] [Craft Scheduler Thread - 6/WARN]: Exception in thread "Craft Scheduler Thread - 6" [11:21:20] [Craft Scheduler Thread - 6/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.6 generated an exception while executing task 29 at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NullPointerException at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:99) at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initAdvancedConfig(ChangeGroupBuilder.java:153) at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initialiseChangeGroups(ChangeGroupBuilder.java:52) at me.armar.plugins.autorank.rankbuilder.ChangeGroupManager.initialiseFromConfigs(ChangeGroupManager.java:47) at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:358) at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) ... 3 more'

For the first one, I know that the error comes from mine at  line 48, column 47 and line 46, column 13 but I don't know what error I've done, I've even try to remove these lines but this doesn't works...

Thanks for your time :) :smile:

**Comment by Staartvin** [comment]
The second error is caused by the first error and the first error is due to an invalid .yml file. You didn't adhere to the YAML standard and Autorank is complaining that it can't read your file. Using http://yaml-online-parser.appspot.com/, I found that you used single quotes in sentences ('), like _l'as_, you'll have to type **two quotes**, like _l''as_ to make it work. This is the correct pastebin: http://pastebin.com/cwRXGLE0

**Comment by wedza** [comment]
Ohh Yes !
Many thanks Staartvin ! All works well finally !
A good review is coming to your spigot page :smiley:

**Comment by Staartvin** [comment]
No problemo!
