### ISSUE TITLE
Can't calculate Mysql global time :/

### ISSUE THREAD

**Issue by Guarmanda** [Armarr/Autorank-2#354]
I had a problem with my mysql database recently, but all data from server times stayed, so I searched a command to create back a new mysql file while adding all local times of servers to it, I also tried to remove the old mysql file, but the new file appear empty. How could I do?

**Comment by Staartvin** [comment]
Do you still have the data.yml? If so, you can run */ar sync* to sync the MySQL database with your local data.yml

**Comment by Guarmanda** [comment]
You saves my life U_u I'll try

**Comment by Staartvin** [comment]
No problemo! Glad I could help!
