### ISSUE TITLE
Autorank disabled.

### ISSUE THREAD

**Issue by Neotras** [Armarr/Autorank-2#357]
here my log

http://pastebin.com/f4x2ejc0

**Comment by Staartvin** [comment]
You will need Statz to run Autorank, like I told you before.

**Comment by Neotras** [comment]
i have statz

**Comment by Staartvin** [comment]
Can you run **/version Statz** and report back as to what it gives?

**Comment by Neotras** [comment]
oh i have the plugin stats installiert not Statz now work thanks

**Comment by Staartvin** [comment]
No problemo! Have fun using Autorank!

**Comment by Neotras** [comment]
thanks
