### ISSUE TITLE
There are invalid groups defined in the config!

### ISSUE THREAD

**Issue by Memermint** [Armarr/Autorank-2#379]
I was looking for solution but I haven't find anything what could help me, need your help!

Console says eror:
[ERROR]: [Autorank] There are invalid groups defined in the config!
[ERROR]: [Autorank] Check your config!

Advanced config: http://pastebin.com/2GGpx1SS

Autorank settings: http://pastebin.com/M6FgrVw7

PermissionsEx: http://pastebin.com/MAXFBUAn

**Comment by Staartvin** [comment]
I see that you don't understand the config format of Autorank just yet. I see at line 16 that you want to players to promote from _Zacatecnik_ to _Hrac_. However, line 11 tells Autorank that it should only check this group when a player is in the group Hrac! That is impossible of course. What you want to do is change **Hrac** (in line 11) to **Zacatecnik**. The same error applies to your second group _Veteran_.

If you still experience any problems, report back here!

**Comment by Memermint** [comment]
Thank you so much for assitance I haven't even get it... Really thank you so much! Now is everything working! It's time to make good review :+1:

**Comment by Staartvin** [comment]
No problemo! Have fun using Autorank!
