### ISSUE TITLE
Autorank disabled - Vault was not found.

### ISSUE THREAD

**Issue by Nesseley** [Armarr/Autorank-2#380]
http://pastebin.com/6ZnFXFbH - Server log.

Version: Autorank 3.8.4
Version: Vault v1.5.6-b49.

I do not use Statz, as I only use autorank for ontime, wich it can do itself after what I understood.

Question 2:
Can I use &globaltime in the /ar check command in the settings file? My friend added it ass a addon a while back, and I didnt see anyhting about it. We coded this in ourself, but then I got this weird thing where it would reset the MySQL database so I'd loose all my ontime. 
On the server who still runs this edited file I get this error when doing /ar check: http://pastebin.com/g4sZUtFt
I really need a globaltime for all my server for my setup to work as I want it too :/

- Nesseley

**Comment by Staartvin** [comment]
What permissions plugin do you have installed? I only get this error when Vault did not find an permissions plugin. 

For question 2, yes you can use &globaltime in the /ar check command. It will work!

**Comment by Nesseley** [comment]
bungeeperms for permissions.

Ok awesome, I hope it doesnt reset again,a dn if it does, il come back to you.

**Comment by Staartvin** [comment]
Could you try to switch permission plugins temporarily and see if that changes things?

**Comment by Nesseley** [comment]
I can but I need bungeeperms in the end. :P
Il check with pex

**Comment by Staartvin** [comment]
Can you show me your server log from when you were running PEX?

**Comment by Nesseley** [comment]
http://pastebin.com/gS7QLQ9b Here you go.

**Comment by Nesseley** [comment]
Hope you had a great vacation dude, cause now it's time to fix vault error xD

http://pastebin.com/XwXsHPsd
Got this error today. Newest autorank and vault if im not mistaken.

**Comment by Nesseley** [comment]
This was fixed in a custom jar he made for me.
