### ISSUE TITLE
Rankup Issue

### ISSUE THREAD

**Issue by AdamIanMurphy** [Armarr/Autorank-2#383]
The plugin works fine, ranking up players as they do the requirements and what not, but as soon as they donate, for a rank, when that rank is applied they cannot rank up anymore

Example, John is Settler, john donates for Valkyrie, he can no longer rank up from settler to Magistrate.

/ar check says "No Requirements found for group valkyrie"

I'm most likely doing something wrong haha, but I have tried to fix it for over a week now and simply can't find the issue.

Thanks for the great plugin, honestly amazing.

**Comment by Nesseley** [comment]
He cannot rank up because he is not in the group "settler".
You have defined Settler -> Magistrate
You have NOT defined valkyrie -> Magistrate.
Not sure why a person who have donated for a rank world like to rank back to normal userranks thoe :/
