### ISSUE TITLE
downloaded, followed tutorial, and error

### ISSUE THREAD

**Issue by namessos** [Armarr/Autorank-2#385]
so, i understood the video, and i configured the ranks myself first and checked it after the video, no issue i inputed everything fine. but now i got ingame errors when trying to type in /ar.
please help me out.

http://pastebin.com/6xpJiemT

**Comment by Staartvin** [comment]
Can you provide your advancedconfig.yml?

**Comment by namessos** [comment]
thank you for answering both posts. i will close this one as i have my config file on the othr one.
