### ISSUE TITLE
problems with autorank

### ISSUE THREAD

**Issue by namessos** [Armarr/Autorank-2#387]
so i had setup auto rank. i had both adv. config and permissionsex up to make sure i didn't mispell the grups and i used the autorank tutorial to help me out and yet i still get errors. please help me out.

permissionsex: http://pastebin.com/WxeK0LX6

autorank adv. config: http://pastebin.com/f2q05Jek

when i get on my server, it says: Rank change of rank 'Student' is invalid. the rnak to 'promote to'
doesn't exist in the perm file. i added apprentice in the autorank and apprentice is in the groups. both spelled correct;y.

**Comment by Staartvin** [comment]
Try to remove the space after the semicolon at the 'rank change'.

**Comment by namessos** [comment]
no, that did nothing. the same message comes out.
