### ISSUE TITLE
Disabling Autorank: Vault was not found

### ISSUE THREAD

**Issue by Killertom63** [Armarr/Autorank-2#388]
## **Info**
Hello, I'm trying to use this on my bungee server. I'm using Pex for my perms, which is connected to it's own DB. 

Whenever I try loading the plugin it just loads and says Disabling Autorank: Vault was not found. 

Nowhere does it say that Vault is needed, so I assume this is a bug. 

## **Version**
v3.8.4

## **Server Version**
Spigot 1.10

## **Log**
http://pastebin.com/1frPChr8

**Comment by Staartvin** [comment]
Do you have an economy plugin installed?

**Comment by Killertom63** [comment]
I installed Vault, that fixed it. You may want to add it as a dependency. And I have essentials.
