### ISSUE TITLE
Autorank isnt keeping up with the amount of Zombie(s) being killed, why?

### ISSUE THREAD

**Issue by YourSenpaiOnly** [Armarr/Autorank-2#402]
Ok so everything seems to be working with autorank, however, when i try to use the command /ar track it continues to tell me that i have 0/50 Zombie(s) killed no matter how many zombies ive killed.

do i need a stats plugin?

**Comment by FrankHG** [comment]
yeah ., you need the statz .. u cant track anything but time just using Autorank-2
