### ISSUE TITLE
Autorank dosnt promote players on PEX but add them to another group ..

### ISSUE THREAD

**Issue by FrankHG** [Armarr/Autorank-2#404]
I have sort of an issue here.. 

I have autorank and groupmanager running just fine in a simple setup with spigot 1.8.9. now im trying to do an upgrade to spigot 1.10.2, autorank 3.8.4 and PEX 1.23.4.

the problem seams to be that autorank instead of 'promoting' players in PEX, it simply adds them to a new rank .. so when all rankups has occured players is in 'all' my ranks.

i also have an 'craft scheduler tread' error on plugin load, but dont think its related:
http://pastebin.com/KL7Rf6Ld

**Comment by Nesseley** [comment]
Simply make it do a command istead of the rank1;rank2 thing?

**Comment by FrankHG** [comment]
Hi Nesseley, ty for your answer .. 
do you have any info on how to do this ?

**Comment by Nesseley** [comment]
results:
            command: '*rank command*'

this should work :)

**Comment by FrankHG** [comment]
Staartvin .. do you agree this was gonna work ?.. 
The comand-thingy dosnt do the actual promotion .. so what was i supposed to put here ?

**Comment by Staartvin** [comment]
You can always try. Please reopen this ticket if you feel it should not be closed.

**Comment by Nesseley** [comment]
You haver to spesify the command, for GM it world be
command: manuadd &p RANKNAME

You have to use Advanced Config to do this.
Example: https://gyazo.com/95718d81be246cb3e732ebf39715e05d

**Comment by FrankHG** [comment]
Hi ., well i finally got around to it .. 
I did the AdvancedConfig and added:
"pex user @p group set Helt" in the commandsection but it still adds my users to multiple groups..

Can i reopen this or should i open a new issue ?

~~Frank .,

**Comment by Staartvin** [comment]
Please open a new issue for administration purposes :)
