### ISSUE TITLE
Error loading UUID

### ISSUE THREAD

**Issue by PretoAlbino** [Armarr/Autorank-2#407]
16.10 17:53:46 [Server] INFO [Autorank] Could not find name of account with uuid: 'f695f42f-d901-334a-950a-fa3505c4efb8'
16.10 17:53:46 [Server] WARN Unexpected token END OF FILE at position 0.
16.10 17:53:46 [Server] WARN at org.json.simple.parser.JSONParser.parse(Unknown Source)
16.10 17:53:46 [Server] WARN at org.json.simple.parser.JSONParser.parse(Unknown Source)
16.10 17:53:46 [Server] WARN at org.json.simple.parser.JSONParser.parse(Unknown Source)
16.10 17:53:46 [Server] WARN at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
16.10 17:53:46 [Server] WARN at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
16.10 17:53:46 [Server] WARN at java.lang.Thread.run(Thread.java:745)
16.10 17:53:46 [Server] WARN Exception in thread "Craft Scheduler Thread - 4" 
16.10 17:53:46 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4 generated an exception while executing task 84

My UUID changes (cracked server) and this happen.

**Comment by Eufranio** [comment]
JSON parsing error.
