### ISSUE TITLE
Autorank 3.8.4-Dev-607-Vault issue

### ISSUE THREAD

**Issue by TheChampTF** [Armarr/Autorank-2#408]
Autorank did not find Vault when it started its boot sequence. This could cause problems!

Odd part is Vault is installed (latest version) and of what I can see the change happened at https://github.com/Armarr/Autorank-2/commit/896eca308830ac9a13ba0d42ae47579a8fbe07e5

**Comment by YourSenpaiOnly** [comment]
What do i need to do then to make it so players dont rank up automatically
