### ISSUE TITLE
Autorank automatcally ranks players up without them doing /ar check why?

### ISSUE THREAD

**Issue by YourSenpaiOnly** [Armarr/Autorank-2#409]
So players usually meet the requirements to rank up and then randomly the plugin will rank them up, this would be fine if a command wasnt set to take their money after ranking up. I have it set on my server so the plugin will take the amount of money that is required for the next rank.

**Comment by Staartvin** [comment]
Fixed in new commit (b577ce341cc158be756d57dd0e3aefe73848f2fe)
