### ISSUE TITLE
Autorank did not find Vault when it started its boot sequence. This could cause problems!

### ISSUE THREAD

**Issue by Killertom63** [Armarr/Autorank-2#411]
I get this error when starting up, but Vault has started and it started before AR. 

I even went in to the plugin.yml and changed Vault from a softdepend to a depend. Still didn't help. 

This could be the issue that I had in ticket #399 @Staartvin

**Comment by Killertom63** [comment]
reloading the plugin after start up, it finds vault fine.

**Comment by Staartvin** [comment]
What version of Autorank are you using?

**Comment by Killertom63** [comment]
3.8.5

**Comment by Killertom63** [comment]
Just to confirm - 
I'm using bungee and using AR and Statz on 3/6 servers as the other 3 do not need it, yet. No-one has access to them. 

AR and Statz are only installed to the 3 servers, and not the others. I also haven't installed it to the Bungee server it's self.

I have then gone to my Hub and done /ar sync then gone to the other servers and done the same. 
______________

Is that correct?

**Comment by Staartvin** [comment]
Yes, that should do it. Can you try the latest dev build of Autorank?

**Comment by Killertom63** [comment]
I don't know how to compile on github. I have you on skype if you can send it over or something?

**Comment by Staartvin** [comment]
Luckily, I already have it compiled for you automatically: http://62.131.38.74:8080/job/Autorank/lastSuccessfulBuild/artifact/target/Autorank-3.8.5.1.jar

**Comment by Killertom63** [comment]
That fixed the hook! Thanks. I do have another issue, 

On different servers, the leader boards are massively different. Like it's not going off global. 

See the images -
Hub - https://gyazo.com/d9e17a91179d2195b89f7357b3143c7c

Survival - https://gyazo.com/17acb2f93223a9b4d0e53785443798bc

**Comment by Staartvin** [comment]
Can you show me your Settings.yml?

**Comment by Killertom63** [comment]
http://pastebin.com/aU229Muu

**Comment by Killertom63** [comment]
They're all the same across all the servers too.

**Comment by Staartvin** [comment]
Can you try performing **/ar leaderboard force** on two servers and see if that correctly sets both leaderboards?

**Comment by Killertom63** [comment]
Ok, yeah that works. Now...last thing and then I promise I'll be out your hair. (You're an amazing dev by the way.)

I kinda' went crazy with using /ar sync and now people have like 10x their time. Is there a way to reset it.

**Comment by Staartvin** [comment]
Haha, welp. To reset database times, you'll have to remove the table so that everything gets reset to 0. There is currently no way of resetting all player times (kind of security).

**Comment by Killertom63** [comment]
Haha opps! Ok. Is that on the Statz DB for time played for the Autorank database, as the Statz one is empty.

**Comment by Staartvin** [comment]
Since you are using Statz's time for Autorank, you'll have to reset the time_played table of Statz yes.

**Comment by Killertom63** [comment]
That's empty?

https://gyazo.com/be3707b9f438d14fc6fb91cdc0b7c9b3

**Comment by Staartvin** [comment]
However, if you want to reset the global time across all servers, you would need to empty Autorank's database (since Autorank uses its own MySQL database for comparing time across all your servers). If you empty Autorank's database and force the leaderboards, then they should get emptied.

**Comment by Killertom63** [comment]
But if my statz time_played table has always been blank could that be an issue in it's self?

**Comment by Staartvin** [comment]
Well, Autorank doesn't use the Statz database if you said it must use global time for the leaderboards.

**Comment by Killertom63** [comment]
Okay, I did that. It kinda' worked minus the top 3 people. Who are currently online on the server. 

https://gyazo.com/83c0df51dc272ced5b7e8499a4d46fe0

**Comment by Killertom63** [comment]
Fixed with time, thank you. :D Best Dev 👍

**Comment by Staartvin** [comment]
No problemo! Glad I could help!
