### ISSUE TITLE
Plugin generates exception and doesn't rank up.

### ISSUE THREAD

**Issue by panslothda** [Armarr/Autorank-2#412]
So i use Vault and Luckperms and wanted to use autorank to make some complicated rankup and different rankup ways for a rpg scenario. i use newest autorank and statz version from spigot  and spigot spigot-BT52-1.10

Now my problem is that it doesnt work. To be more exact i have the following in the advanced config.yml

ranks:
   default:
        requirements:
            gamemode:
                value: 0
        results:
            rank change: default;wanderer

So it should rankup a person automatically from default to wanderer when the person joins the server since the requirement is that the person is in gamemode 0. Which does not work tough. I have no idea though why that is. the group default and wanderer are both setup in luckperms.

Another thing that might(?) be connected is that i get quite some exceptions in the console cause by autorank.

console output: http://pastebin.com/ks354mBC

**Comment by Staartvin** [comment]
Could you also put your config in pastebin?

**Comment by panslothda** [comment]
Config: http://pastebin.com/K8TkY7gC
and settings: http://pastebin.com/V6DxMExP

Its mostly the basic configuration since i didnt change to much yet. I just renamed ranks and put it that it automatically ranks someone up when he joins.

**Comment by panslothda** [comment]
So after a day fo keeping it running i have following problems: First of all the plugin generates hundreds of exception in the console. everytime i execute any command it spams the console with an exception.

Sometimes the command works and sometimes not. as an example i can use /ar set player 1h and it tells me it did it but checking /ar leaderboard later on still shows old stuff and even after server restart didn't change it.

If i do /ar check player and the player is oped it gives me an internal error occured and if the player is non oped it works.

I have yet to test other rankup possibilities to see if that works.

I would really love to use your plugin since i didnt find another one that has that many features and mcmmo integration. If there's any kind of help i can give you to debug the problem from testing specific scenarios to logfile or snapshots please let me know :)

**Comment by Staartvin** [comment]
What commands are you trying to perform? If it keeps giving errors, could you true completing reseting the folder (deleting Autorank folder, let Autorank recreate a new one).

**Comment by panslothda** [comment]
Well i only used what i mentioned in my post before. Not really much to add there.


But i will test all the autorank stuff to see if all the exceptions it generates in the console have a impact or if the main stuff still works.

**Comment by panslothda** [comment]
Ok here's a more in depth what is wrong description:
first of all my settings http://pastebin.com/CZ6HfKaB and config file http://pastebin.com/UDF1uEn7 

I deleted autorank folder and added those 2 files again to make sure its all new.


So first of all during 5 minutes of server running i got the following 3 random 
" Plugin Autorank v3.8.5.1 generated an exception while executing task XX "
http://pastebin.com/XQpdLTSz

Then when i issue /ar check it gives me a big red a internal error occured blabla text and console tells me this: http://pastebin.com/ScgsbkgB
This does not matter if i do it for oped or normal player or wahtever it gives me that. if i issue /ar check directly or /ar check player both internal error.

Then it doesn't auto rankup. When i issue /ar leaderboard there are some numbers on it that seem to be somewhat accurate but when i do /ar set player 1h 59m the leaderboard afterwards shows me the time as -1m for that player..... and if i do like /ar set player 30m it just doesn't add it.

I even just waited for straight 2 hours with a new user on the server after i deleted autorank folder but nada didnt rankup.



Any way i can help you debug?

**Comment by panslothda** [comment]
Can be closed...... a line was one space off in the config file that let the whole thing not work....

Im terribly sorry for the inconvenience

**Comment by Staartvin** [comment]
No problem! Glad you got it fixed!

**Comment by panslothda** [comment]
On a sidenote (sry to bug you again but didnt wanna open a extra thread)

since i now was able to test my config. when i put this inside the file:
        requirements:
            mcmmo skill level: 
                value: 50;Archery
            mcmmo skill level:             
                value: 50;Swords                
            mcmmo skill level: 
                value: 50;Axes

It only takes the axes as requirements. Is there some way to make all 3 of the skills requirements for rank up?
