### ISSUE TITLE
Make multiple requirements of mcmmo skills

### ISSUE THREAD

**Issue by panslothda** [Armarr/Autorank-2#415]
So i want to have a requirement of needing 3 mcmmo skills on a certain level as a rankup requirement.

Now i tried multiple ways and the closest i got was: 
            mcmmo skill level: 
                value: '50;Archery,50;Swords,50;Axes'

But that is just archery or swords or axes. Is there any way i can make this into archery and swords and axes?

**Comment by Staartvin** [comment]
Yes, you can do this. You'll need to have three different mcmmo skill level requirements, so 'mcmmo skill level1'  with archery, then 'mcmmo skill level2'  with swords, etc. Don't write the quotes though, those are just for you to clarify how it works.

**Comment by panslothda** [comment]
Ah ok great thank you very much :)

Maybe add that to the wiki as well? because i searched for multiple values for same requirement and didn't find anything. or i just suck as searching which is true as well :D
