### ISSUE TITLE
Promotion Issue

### ISSUE THREAD

**Issue by AntZaro** [Armarr/Autorank-2#420]
I'm having an issue with the way Autorank is promoting people. This is with me using a permissions plugin called LuckPerms (my normal server is GroupManager, but I'm testing LuckPerms). So basically, Autorank is adding parent groups for each rank up, but it's not changing the person's primary group.

**What Autorank must be doing:**
/perm user [user] parent add [rank]
This is adding the new rank as a parent, and removing the previous parent rank, whilst leaving the default server rank as their primary group.

**What I want Autorank to do:**
/perm user [user] parent set [rank]
This command would set the user's primary group as the new rank.

Is there anyway this could be changed? I want to switch off of GroupManager, but Autorank would have to be ranking people correctly for me to do that.

**Comment by Nesseley** [comment]
The solution to this is to not use the option "rank change rank1:rank2" but set the command you want yourselv in the option "commands"

**Comment by Staartvin** [comment]
@Nesseley is right. Autorank uses the standard approach provided by Vault, but sometimes this doesn't result in the correct outcome. You can also let Autorank perform commands, so you would add the following command: _perm user &p parent set [rank name of your desired rank]_

**Comment by AntZaro** [comment]
Thank you guys. I was using the simple config, and even though I looked at the advanced one, I didn't realise I was able to do that. So glad this is sorted; hopefully the new update doesn't confuse me again haha. Thanks again!

**Comment by Staartvin** [comment]
Glad it got solved!
