### ISSUE TITLE
Is Autorank compatible with T-Perms?

### ISSUE THREAD

**Issue by P0Pss** [Armarr/Autorank-2#428]
Im using https://www.spigotmc.org/resources/t-perms-permission-plugin-by-tainlastv.18823/ and want to know if the two are compatible.
I keep getting a warning "<AUTORANK> Warning: Rank change of rank 'Survivor' is invalid. The rank to 'promote to' doesn't exist in the perm file."

**Comment by Staartvin** [comment]
I've never tested it with T Perms, so there is a chance it does not work. Can you show me your advanced config?

**Comment by P0Pss** [comment]
`#############################################################################
#                                                                           #
#                   Autorank Advanced Config                                #
#                                                                           #
#   Please use the SimpleConfig unless you know what you are doing and      #
#   need functionality that the SimpleConfig doesn't provide.               #
#                                                                           #
#############################################################################

ranks:
    Survivor:
        requirements:
            time: 1h
            gamemode: 0
            blocks broken: 15;1
        results:
            rank change: Survivor;Miner
            command: '/tperms player group set &p Miner'
            message: 'Congratulations, you have survived the surface long enough to collect resources for a better life your yourself, you are now a Miner!'
    Miner:
        requirements:
            time:
                value: 4h
            gamemode:
                value: 0
            mobs killed:
                value: 100
        results:
            rank change: Member;Vip
            command: 'say &p has just been promoted to VIP!; give &p 1 100; tell &p You have just earned 100 stone!'
            message: 'Congratulations, you are now a vip.'
            
    Hunter:
    Veteran:
    Overlord:
# new requirements and results can be added by other plugins that hook into the Autorank API
# these are the ones that are included in the main plugin:
# 
#   requirements:
#       time: 1d 1h 1m
#       exp: 20 (level)
#       money: 2000 (requires vault ! Player has to have at least this amount of money)
#       world: world_nether (player has to be in this world to get ranked)
#       gamemode: 1 (player has to have a certain gamemode, 0 = Survival mode, 1 = Creative mode, 2 = Adventure mode)
#       has item: id(;amount;data;name;false/true) (checks the players inventory for the item, the name would be the display name of the item. When the false/true (boolean) parameter is true, the player should have the item with the given display name, if it is false, the player only needs the specific amount and material type.)
#       blocks broken: id(;amount;data;name) (a player has to have broken x amount blocks of item id and data) (Requires Statz) (when no data or id is given, it will check total blocks)
#       Example: break 10 magenta wool would be: 'blocks broken: 35;10;2' 35 = itemid, 10 = amount, 2 = damagevalue
#       blocks placed: id(;amount;data;name) (a player has to have placed x amount blocks of item id and data) (Requires Statz) (when no data or amount is given, it will check total blocks)
#       votes: 10 (player has to have voted at least 10 times) (Requires Statz and Votifier)
#       damage taken: 10 (player has to have taken 10 damage) (damage is not counted in hearts) (Requires Statz)
#       mobs killed: 5;spider (player has to have killed 5 spiders) (if no entity is specified, then any kill counts) (Requires Statz) (for a list of entities: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html) Can also use WITHER_SKELETON, 
#       location: x;y;z;world;radius (player has to be in a location or within its radius)
#       faction power: 10 (Amount of power a faction has to have) (Requires Factions)
#       players killed: 10 (Player has to kill at least 10 players) (Requires Statz)
#       global time: 10d 1h 5m (Player has to be online for at least 10 days, 1 hour and 5 mins) (Global time is the accumulated time over all servers you have connected the MySQL database with)
#       total time: 50d 1h (Player has to be with this server for at least 50 days and 1 hour) (The time from when the player joined for the first time is the reference point. This means that when a player has joined 3 weeks ago, his 'total time' = 3 weeks)
#       blocks moved: 1000;0 (Player has to move at least an x amount of blocks. Second argument is what kind of movement: 0=walk, 1=boat, 2=train, 3=pig, 4=pig in train, 5=horse) (Need Statz for this)
#       worldguard region: TestRegion (Player has to be in a certain WorldGuard region) (requires WorldGuard)
#       mcmmo skill level: 100;mining (Player has to have at least level 100 in mining) (requires McMMO)
#       mcmmo power level: 100 (Player has to have at least power level 100) (requires McMMO)
#       permission: i.need.a.permission (Player has to have this permission)
#       fish caught: 10 (Player has to have caught at least 10 fish) (requires Statz)
#       items crafted: 7 (Player has to have crafted at least 7 items) (requires Statz)
#       times sheared: 15 (Player has to have sheared at least 15 sheep) (requires Statz)
#       essentials geoip location: Netherlands (Player has to be in the area 'Netherlands') (requires Essentials GeoIP)
#       in biome: river (Player has to be in biome 'river') (a list of all biomes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
#       food eaten: 10;PORK (Player has to eat at least 10 Pork chops) (Food type can be omitted to include any type of food) (Statz required)
#       acidisland level: 10 (Player needs to have at least an island level of 10) (AcidIsland required)
#       askyblock level: 10 (Player needs to have at least an island level of 10) (ASkyBlock required)
#       javascript: Player.getHealth() > 15;You need at least 15 hearts of health. (This first part must be true for this evaluations to be true, the second part is the description that is shown.)
#       jobs current points: 10 (Player needs to have at least 10 points (at the moment of checking) in Jobs) (requires Jobs)
#       jobs total points: 100 (Player needs to have at least 100 points in total in Jobs) (requires Jobs)
#       jobs level: 50;mining (A player has to have at least level 50 in job 'mining') (requires Jobs)
#       jobs experience: 100;mining (A player needs to have at least 100 exp in the job 'mining') (requires Jobs)
#       grief prevention claims: 100 (A player needs to have at least 100 claims in Grief Prevention) (requires GriefPrevention)
#       grief prevention claimed blocks: 150 (A player needs to have at least 150 blocks claimed in Grief Prevention) (requires GriefPrevention)
#       grief prevention remaining blocks: 20 (A player needs to have at least 20 blocks left over to claim in Grief Prevention) (requires GriefPrevention)
#       grief prevention bonus blocks: 60 (A player needs to have at least 60 bonus blocks in Grief Prevention) (requires GriefPrevention)
#       has achievement: 10 (A player needs to have at least 10 achievements.)
#       (also possible:) has achievement: BREED_COW (A player has to have a specific achievement. For a list of achievements, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Achievement.html)
#       rpgme skill level: 20;mining (Player has to have at least level 20 in mining in RPGme) (requires RPGme)
#       rpgme combat level: 100 (Player has to have at least combat level 100 in RPGme) (requires RPGme)
#
#   results:
#       rank change: new-rank
#       rank change: old-rank; new-rank
#       rank change: old-rank; new-rank; world (only works for permissions plugins that support this)
#       message: 'You got ranked up'
#       command: 'say &p hi; give &p 1 100'(executes a console command. &p will be replaced by the player name) You can perform more commands with the ';' sign.
#       effect: STEP_SOUND;8 (first argument is the effect name, second is the effect data. For a list of possible effects go to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html)
#       tp: x;y;z;world;yaw;pitch (tp: 0;0;0;world_nether;1.0;2.0)
#       firework: target;power;type;R;G;B (Spawn a firework with on a player or spawn, with specified power, type and RGB colour) (target can be 'player' or 'spawn', power is an integer, type is a type (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/FireworkEffect.Type.html), R;G;B is a RGB colour code (see http://www.rapidtables.com/web/color/RGB_Color.htm))`

The permissions file is 
`permissions:
  groups:
    default: Survivor
    Owner:
      chatprefix: '&8[&7Survivor&8]'
      tabprefix: '&7'
      tabplace: 0
      permissions:
      - tperms.commands.use
    Overlord:
      parent: ''
      chatprefix: '&8[&7Overlord&8]'
      tabprefix: '&7'
      tabplace: 0
      permissions:
      - 
      
    Veteran:
      parent: ''
      chatprefix: '&8[&7Veteran&8]'
      tabprefix: '&7'
      tabplace: 0
      permissions:
      - 
      
    Hunter:
      parent: ''
      chatprefix: '&8[&7Hunter&8]'
      tabprefix: '&7'
      tabplace: 0
      permissions:
      - 
      
    Miner:
      parent: ''
      chatprefix: '&8[&7Miner&8]'
      tabprefix: '&7'
      tabplace: 0
      permissions:
      - 
    
    Survivor:
      parent: ''
      chatprefix: '&8[&7Survivor&8]'
      tabprefix: '&7'
      tabplace: 0
      permissions:
      - 

  grouplist:
  - guest
  users:
    tainlastv:
      group: guest
      permissions: []`

I didnt finish either cause of the autorank issue and didnt want to restart if I needed a different plugin

**Comment by P0Pss** [comment]
I decided to use a different permissions plugin and it works
