### ISSUE TITLE
Data to MySQL - merge request

### ISSUE THREAD

**Issue by Imothep80** [Armarr/Autorank-2#429]
Hi,

at first...cool work man :)

Now my Server is growing and i get a Problem. At the first time i don't save my data to MySQL. Have you Programm or Funktion to merge the data?
This would be nice because i love this plugin.

**Comment by Staartvin** [comment]
You can turn on MySQL in the settings and then run /AR sync to sync your local file with your database.

**Comment by Imothep80** [comment]
thx a lot. 👍
