### ISSUE TITLE
Track crafting of specific items? 

### ISSUE THREAD

**Issue by smmalloy** [Armarr/Autorank-2#430]
Hello, 

I am trying to track crafting of specific items, however I appear to be failing. Statz will track specific items crafted, how do I implement this with Autorank? Currently I have got the following in my advanced config. 
101 being IronBars, and 320 being the ammount needed to craft. Is this possible?
```

    Blacksmith1:
        requirements:
            time:
                value: 3d        
            items crafted1: 320;101
        results:
            rank change: Blacksmith1;Blacksmith2
            command: 'say &p has just been promoted to Blacksmith2!'
            message: 'Congratulations, you are now a Second Grade Blacksmith.'
```

**Comment by Staartvin** [comment]
In the past Autorank supported Stats, which didn't track which item were crafted, only how many. Statz does track what items are crafted, but Autorank still needs to switch over to a different setup where it can support this new tracking. I'm working on it!
