### ISSUE TITLE
Difference between "time" and "global time"

### ISSUE THREAD

**Issue by FelixLudi** [Armarr/Autorank-2#436]
What is the difference between this:
time | Player needs x amount of time | %d %h %m | 1d 1h 1m | Needs 1 day + 1 hour + 1m of play time
and this:
global time | Player has to be online for x amount of time on your global Minecraft server network | %d %h %m | 60m | Needs to be online for a total of 60 minutes

Basically I want people that have played more on the server to have higher rankings.. ex. first one is Newbie (0h), 2nd one is Member (2h) Experienced (50h) etc etc.

Can someone clarify this and/or suggest another type of counting (I wont use total time because thats not what I need).

Thank you.

**Comment by Staartvin** [comment]
Time is the time a player played on your server locally. Global time is the cumulative time played across all your servers you set up a MySQL database for. If you did not do this, then just use local time.

**Comment by FelixLudi** [comment]
By local time you mean the first one, right?

**Comment by Staartvin** [comment]
Yes, 'time'. Global time is 'global time'.

**Comment by FelixLudi** [comment]
Thank you

**Comment by Staartvin** [comment]
No problem!
