### ISSUE TITLE
Choosing paths issues

### ISSUE THREAD

**Issue by FrozenBeard** [Armarr/Autorank-2#438]
using 3.8.5.1-Dev-642

1. If there is only 1 path available you SHOULD NOT have to select it, it should auto be selected for /ar check
2. If you complete a path, it should NOT be displayed when you do /ar view list, if I rank up, I shouldn't have that path displayed to me if I have already ranked up! this is so confusing to players.

**Comment by Staartvin** [comment]
Right now the paths system is in development. Thanks for the early feedback :)

To answer your questions:
1. I'm considering adding an option to the paths that allow you to set whether an path will automatically be chosen by Autorank if the player meets all the prerequisites.
2. Good call. I'll add that!

**Comment by FrozenBeard** [comment]
Ah superb! I was struggling with figuring out everything, as Im literally using an ancient version that worked with Stats2 still!! I only today started experimenting with the latest and greatest of autorank.

Fantastic! 

There needs to be some way to show the order of rank upgrades, a player wont know what order they have to do ranks in unless they check each one individually. Especially with a linear design for ranks as you go through rank1 > rank2 > rank3 > rank4 > rank5 > rank6.

For me, as i'm upgrading from such an ancient version of autorank, I have thousands of players that have already ranked up (Im not sure if this data gets converted over to this new version of AR).
I have an issue; People that are higher ranks say a rank6 could do /ar choose rank1 and it will let them! I don't want a later rank to be able to down-rank, since there is no way to show the order of ranks, then new players will have no idea what rank they will be upgrading/downgrading too!

This shouldn't be an issue for new players, as they have to do the first rank to get to the second.

Is there a way to check that they can only rank if they are a current rank atm? Like you can only go from Rank1 to Rank2 if you are Rank1.
Like would that be a prerequisites?

Do we still have to format it `rank change: Sailor;Carpenter`? or do we just use the old name?

**Comment by Staartvin** [comment]
Many questions at once!

Here are a few concise answers:
1.  **People from rank6 can do /ar choose rank1. I don't want that!**
    - That's indeed solvable by using prerequisites. Just add a 'in group' prerequisites with 'rank1' and only players that are rank1 can choose that path.
2. **I'm not sure if data gets backed up from older versions**
    - Right now, it doesn't. I'm working on adding a converter that will seemingly transform your old data to the new format. I suggest you test server for now, as this version of Autorank is clearly not ready for production yet!
3. **Do we still have to format it to rank change: ....**
    - You can do that if you want, but you can also only provide the rank you want to **promote to**, and Autorank will try to figure out what rank the player previously had.


Hope that clears something up!

**Comment by FrozenBeard** [comment]
Thanks for the information! This gives me a better understanding of how the plugin works.

**2.** It looks like my PlayerData.yml is still being used, as it was moved into a PlayerData folder, from all the existing ranks people have already ranked to, I cannot start again with the amount of users I have, is PlayerData being used from my ancient install? I cant tell as im the admin and I never did the ranking process. I am using a test server to try all this out, but I wanted to get my autorank updated either tonight or tomorrow, as it took me 2 days for my stats2 data to convert to stats3, which means the longer I leave it the more data gets lost as the servers constantly busy.
**4.** How does /ar leaderboard pull its data? I saw it working with my old data after I started using the latest version, then all of a sudden it just displayed my username, I cant figure out why it did this, I didn't touch the data.

**Comment by Staartvin** [comment]
3. At this moment, data is not being transferred from your ancient install Autorank 4. I **do not** recommend running Autorank 4.0 on production in its current state. I'll be implementing a way to transfer your data to the new version, but that's not done yet.
4. Depending on the ancient install version you had, the leaderboard might work, it might not. However, once your old data is loaded correctly, the leaderboards will restore themselves.

**Comment by FrozenBeard** [comment]
**3 & 4.** Autorank 4.0? I can't see Autorank 4 anywhere, this is whats really confused me as your Docs started on a AR 4.0 Wiki, but your dev says its "Autorank version 3.8.5.1-Dev-642" thats the version im using, Crap so now I've put all the work into making Paths.yml work, does this mean I will have to backdate to a version that does work with my data? Its literally the last version that worked with stats2 I was coming from. So;
a) What's the latest version I should use to keep my data?
b) Will I have to ditch the paths.yml?
c) Since im testing with "3.8.5.1-Dev-64" which im now led to belive is actually version 4, if I backdate to a more stable version will I have to regenerate/convert from the old data again? or is V4.0 the same data structure as the latest stable version?

**Comment by Staartvin** [comment]
Yes, the version you had before was the last one running Stats 2. You are now running a development build that is close to being 'Autorank 4.0' (you can see 'dev') in the version string. 

a) Try going back to the old version you had before. Otherwise, the last official version is Autorank 3.7.1 which has Stats 3 support.
b) The Paths.yml file can be safely ditched, but you'll need it after you upgrade to Autorank 4.0
c) See top answer; basically if you run Autorank 3.7.1, it will try to read your old data instead of the new files that were created in the dev version.

**Comment by FrozenBeard** [comment]
a) Why not go to 3.8.5.1? I have my stats converted now to stats3, so I really want to use the latest, is 3.7.1 really the only version that would allow me to use my data? is there no way to convert then convert again? does 3.7.1 convert and then use say 3.8.5.1 to convert it again to the new format? 3.7.1 is 13 versions behind from Jan 23, 2016... What about MySQL? I just noticed there is a MySQL option, could I use this and keep my data? 
b) Gotcha, so part of V4 👍 

Thanks for replying to all my questions man, I have no idea what to do now, as I spent the entire day figuring out how I would get myself all updated on Stats & Autorank, but I've now hit a brick wall with the data not being converted. Maybe theres another one off way I could move the data, maybe using Sublime Text or something...

**Comment by Staartvin** [comment]
Ah sorry, I keep mentioning 3.7.1, but I meant 3.5.8.1, so that's the latest official build.

**Comment by Staartvin** [comment]
I'll write up a document on the wiki on how to move data from 3.8.5.1 to 4.0 (and dev versions).

**Comment by FrozenBeard** [comment]
Hey @Staartvin sounds good to me, I did end up trying 3.7.1 and the data wasn't picked up, when I did /ar check <username> it said the player hadn't logged into the server, I pushed over the playerdata, UUID's and Data.yml file, I even tried the import for old data and I also tried the MySQL, Ill retry with the 3.8.5.1 to see if I can get the data being picked up. Any tips on how to move from 3.5.1 (my current data is this) to  3.8.5.1? It should just work right?

**Comment by Staartvin** [comment]
Solved over Skype :)

**Comment by FrozenBeard** [comment]
If anyone finds this page/ticket through Google search, it looks like a Wiki page has now been created on how to convert data to Autorank 4, I guess thats why this ticket was closed! :)
https://github.com/Armarr/Autorank-2/wiki/How-do-I-upgrade-to-Autorank-4.0-(or-above)%3F
