### ISSUE TITLE
"There are invalid groups defined in the config"

### ISSUE THREAD

**Issue by Waplax** [Armarr/Autorank-2#441]
I'm having a problem with autorank where it says in console "There are invalid groups defined in the config! Check your config!". I tried doing this over and over checking anything i could think of, so i decided to try and reinstall the Autorank plugin completely, downloaded the files, deleted it and added the AR plugin again, but it keeps giving me the same message in console, even though everything is default.

Any help on this would be greatly appreciated!

**Comment by Staartvin** [comment]
Could you give me your advanced config and permission groups?

**Comment by Waplax** [comment]
Any chance you could tell me where to find the permission groups you need? It's the first time i'm setting up a server, and i had a lot of help with autorank when it was set up at first, so i'm not entirely sure which one that is(Hence why i've been tyring whatever i could think of with plugins and such)..

This is my Advanced Config though:
http://pastebin.com/ZHkRi1vy

**Comment by Staartvin** [comment]
What permission plugin are you using?

**Comment by Staartvin** [comment]
Because that's the plugin that manages your permission groups.

**Comment by Waplax** [comment]
I've got GroupManager(Essentialsx GroupManager)

**Comment by Staartvin** [comment]
There should be  a Group manager folder that you can use to find the  groups you defined.

**Comment by Waplax** [comment]
Alright, Hoping this is the right thing then.
http://pastebin.com/zhM5uKFY

**Comment by Staartvin** [comment]
Yep, those are correct.

**Comment by Staartvin** [comment]
So it's telling you (in the console) that there are errors? Could you log in to your server to see what the error is about? Autorank will tell you when you log in.

**Comment by Waplax** [comment]
There was a constant spam of chat messages before saying there was a problem with pioneer rank(i found out i had a big P instead of small somewhere which messed it up, then when i fixed that, this(http://prnt.sc/dynus2) error popped up, couldn't fix it, Posted elsewhere with no responses and decided  to try and figure out about console, hoping it might lead to an overall fix.

**Comment by Staartvin** [comment]
Welp, it says that Autorank cannot find the Legend group. Did you type it correctly? Correct spelling?

**Comment by Waplax** [comment]
Unless you can see something in those 2 pastebins i made, which might be the problem then i really have no idea.. Everything seems to be written correctly..

**Comment by Waplax** [comment]
I'd like to apologize for wasting your time on this.. There was never a real problem with this, i had forgotten to move the groups to the new world after resetting it. As soon as i did, none of this was a problem anymore. Thanks a bunch for trying to help though, much appreciated! :)

**Comment by Staartvin** [comment]
No problem, can happen to anyone! Glad I could help :)
