### ISSUE TITLE
Autorank check interval

### ISSUE THREAD

**Issue by PyricDemon** [Armarr/Autorank-2#777]
I need a way to give a player a rank pretty much as soon as they join (which works), but Autorank keeps throwing a message in the console every 30 seconds saying "[Sun, 28. Feb 2021 10:39:20 EST INFO] <Autorank warning> (High priority): The time between time checks is less than 1, which is illegal!" could you help me disable this or create a patch for this?

**Comment by Staartvin** [comment]
What is the interval setting in your settings file?

**Comment by PyricDemon** [comment]
Zero.

**Comment by Staartvin** [comment]
It needs to be at least one. You don't have to put it to zero for Autorank to check a player at login.

**Comment by PyricDemon** [comment]
the thing is I have multiple worlds (SMP, Factions, Creative) and they each have different permissions, the only rank giving plugin I could find was this one, and when someone joins hub yeah they get hub instantly, but when they join SMP they don't get that rank until a minute later so they need to sit and wait until they get the rank, but setting it to 0 makes them get the rank instantly on joining the next world. I just need a way to stop autorank from saying that.

**Comment by PyricDemon** [comment]
I guess I'll have to continue my search for a better plugin or just create my own in a couple of months time

**Comment by PyricDemon** [comment]
Nvm I'm self-hosting again and I switched to bungeecord, this is no longer a problem, and your plugin is very good. Sorry for causing you a problem.
